export const IMPORTED_NPCS = [
  {
    "id": 1,
    "name": "Aldeano",
    "npcType": 0,
    "heading": 3,
    "body": 18,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 2,
    "name": "Gallo",
    "npcType": 0,
    "heading": 3,
    "body": 5,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 8,
    "gold": 0
  },
  {
    "id": 3,
    "name": "Cerdo",
    "npcType": 0,
    "heading": 3,
    "body": 6,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 35,
    "minHit": 1,
    "maxHit": 2,
    "def": 0,
    "exp": 15,
    "gold": 0
  },
  {
    "id": 4,
    "name": "Vaca",
    "npcType": 0,
    "heading": 3,
    "body": 366,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 45,
    "minHit": 1,
    "maxHit": 3,
    "def": 2,
    "exp": 20,
    "gold": 0
  },
  {
    "id": 5,
    "name": "Sacerdote",
    "npcType": 1,
    "heading": 3,
    "body": 49,
    "head": 3,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 6,
    "name": "Guardia Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 15,
    "head": 0,
    "movement": 5,
    "agresivo": false,
    "hp": 1000,
    "minHit": 115,
    "maxHit": 250,
    "def": 30,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 7,
    "name": "HerreriaGeneral",
    "npcType": 0,
    "heading": 3,
    "body": 16,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 8,
    "name": "Comidas",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 9,
    "name": "Granjero Norte Ullathorpe",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 10,
    "name": "Bardo",
    "npcType": 0,
    "heading": 3,
    "body": 17,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 315,
    "minHit": 35,
    "maxHit": 80,
    "def": 0,
    "exp": 320,
    "gold": 0
  },
  {
    "id": 11,
    "name": "Aldeana",
    "npcType": 0,
    "heading": 3,
    "body": 19,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 12,
    "name": "SastreGeneral",
    "npcType": 0,
    "heading": 3,
    "body": 19,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 13,
    "name": "Guardia del Caos",
    "npcType": 2,
    "heading": 3,
    "body": 140,
    "head": 203,
    "movement": 11,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 14,
    "name": "Alquimista",
    "npcType": 0,
    "heading": 3,
    "body": 34,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 15,
    "name": "Tabernero",
    "npcType": 0,
    "heading": 3,
    "body": 388,
    "head": 17,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 16,
    "name": "Herrero General Ullathorpe",
    "npcType": 0,
    "heading": 3,
    "body": 281,
    "head": 5,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 17,
    "name": "SastreRinkel",
    "npcType": 0,
    "heading": 3,
    "body": 260,
    "head": 13,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 18,
    "name": "Herrero General Orac",
    "npcType": 0,
    "heading": 3,
    "body": 110,
    "head": 303,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 19,
    "name": "Herrero Armaduras Rinkel",
    "npcType": 0,
    "heading": 3,
    "body": 221,
    "head": 305,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 20,
    "name": "Herrero Armas Rinkel",
    "npcType": 0,
    "heading": 3,
    "body": 254,
    "head": 304,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 21,
    "name": "SastreBanderbill",
    "npcType": 0,
    "heading": 3,
    "body": 395,
    "head": 171,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 22,
    "name": "Herrero Armas Suramei",
    "npcType": 0,
    "heading": 3,
    "body": 22,
    "head": 8,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 23,
    "name": "Herrero Armaduras Suramei",
    "npcType": 0,
    "heading": 3,
    "body": 58,
    "head": 14,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 24,
    "name": "Banquero",
    "npcType": 4,
    "heading": 3,
    "body": 37,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 25,
    "name": "Herrero Armas Nueva Esperanza",
    "npcType": 0,
    "heading": 3,
    "body": 281,
    "head": 15,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 26,
    "name": "Herrero Armaduras Nueva Esperanza",
    "npcType": 0,
    "heading": 3,
    "body": 22,
    "head": 11,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 27,
    "name": "Sastre Tiama",
    "npcType": 0,
    "heading": 3,
    "body": 268,
    "head": 9,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 28,
    "name": "SastreArghal",
    "npcType": 0,
    "heading": 3,
    "body": 97,
    "head": 172,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 29,
    "name": "SastreLindos",
    "npcType": 0,
    "heading": 3,
    "body": 401,
    "head": 107,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 30,
    "name": "SastreOrac",
    "npcType": 0,
    "heading": 3,
    "body": 400,
    "head": 72,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 33,
    "name": "Leñador",
    "npcType": 0,
    "heading": 3,
    "body": 111,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 34,
    "name": "Propiedades Ullathorpe",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 35,
    "name": "Propiedades Nix",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 36,
    "name": "Banquero",
    "npcType": 4,
    "heading": 3,
    "body": 37,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 37,
    "name": "Herrero General Lindos",
    "npcType": 0,
    "heading": 3,
    "body": 93,
    "head": 10,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 38,
    "name": "ArmadurasGeneral",
    "npcType": 0,
    "heading": 3,
    "body": 54,
    "head": 306,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 39,
    "name": "SastreNix",
    "npcType": 0,
    "heading": 3,
    "body": 123,
    "head": 473,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 40,
    "name": "Ben",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 41,
    "name": "Pescador",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 2,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 42,
    "name": "Comidas Newbie Dungeon",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 4,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 43,
    "name": "Tabernero Newbie Dungeon",
    "npcType": 0,
    "heading": 3,
    "body": 388,
    "head": 17,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 44,
    "name": "Carpintero",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 2,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 45,
    "name": "Espiritu",
    "npcType": 0,
    "heading": 3,
    "body": 8,
    "head": 500,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 46,
    "name": "MagoUllathorpe",
    "npcType": 0,
    "heading": 3,
    "body": 50,
    "head": 3,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 47,
    "name": "MagoNixMagos",
    "npcType": 0,
    "heading": 3,
    "body": 140,
    "head": 6,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 48,
    "name": "Minero",
    "npcType": 0,
    "heading": 3,
    "body": 100,
    "head": 2,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 49,
    "name": "Guardia Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 15,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 1000,
    "minHit": 150,
    "maxHit": 250,
    "def": 30,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 50,
    "name": "Tabernero Mesón Hostigado",
    "npcType": 0,
    "heading": 3,
    "body": 388,
    "head": 17,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 51,
    "name": "MagoBanderbill",
    "npcType": 0,
    "heading": 3,
    "body": 130,
    "head": 11,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 52,
    "name": "Propiedades Banderbill",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 53,
    "name": "Roksar",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 54,
    "name": "SastreUllathorpe",
    "npcType": 0,
    "heading": 3,
    "body": 356,
    "head": 472,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 55,
    "name": "Herrero Armas Banderbill",
    "npcType": 0,
    "heading": 3,
    "body": 22,
    "head": 6,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 56,
    "name": "Herrero Armaduras Banderbill",
    "npcType": 0,
    "heading": 3,
    "body": 94,
    "head": 12,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 57,
    "name": "Banquero",
    "npcType": 4,
    "heading": 3,
    "body": 37,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 58,
    "name": "Pescador",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 101,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 59,
    "name": "Leñador",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 60,
    "name": "Entrenador",
    "npcType": 3,
    "heading": 3,
    "body": 57,
    "head": 6,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 61,
    "name": "MagoLindos",
    "npcType": 0,
    "heading": 3,
    "body": 79,
    "head": 12,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 62,
    "name": "Propiedades Lindos",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 63,
    "name": "Sacerdote",
    "npcType": 1,
    "heading": 3,
    "body": 49,
    "head": 3,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 65,
    "name": "Gallo",
    "npcType": 0,
    "heading": 3,
    "body": 5,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 8,
    "gold": 0
  },
  {
    "id": 66,
    "name": "Cerdo",
    "npcType": 0,
    "heading": 3,
    "body": 6,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 35,
    "minHit": 1,
    "maxHit": 2,
    "def": 0,
    "exp": 15,
    "gold": 0
  },
  {
    "id": 67,
    "name": "Vaca",
    "npcType": 0,
    "heading": 3,
    "body": 366,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 45,
    "minHit": 1,
    "maxHit": 3,
    "def": 2,
    "exp": 20,
    "gold": 0
  },
  {
    "id": 68,
    "name": "Pescador",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 102,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 69,
    "name": "Argal",
    "npcType": 0,
    "heading": 3,
    "body": 3,
    "head": 2,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 70,
    "name": "Herrero armaduras Illiandor",
    "npcType": 0,
    "heading": 3,
    "body": 93,
    "head": 11,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 71,
    "name": "Herrero Armas Illiandor",
    "npcType": 0,
    "heading": 3,
    "body": 254,
    "head": 306,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 72,
    "name": "Jerek",
    "npcType": 5,
    "heading": 3,
    "body": 409,
    "head": 306,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 73,
    "name": "Guardia Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 62,
    "head": 101,
    "movement": 5,
    "agresivo": false,
    "hp": 1000,
    "minHit": 150,
    "maxHit": 250,
    "def": 30,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 74,
    "name": "Águila",
    "npcType": 0,
    "heading": 3,
    "body": 59,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 40,
    "minHit": 4,
    "maxHit": 15,
    "def": 0,
    "exp": 75,
    "gold": 0
  },
  {
    "id": 75,
    "name": "Cuervo",
    "npcType": 0,
    "heading": 3,
    "body": 68,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 30,
    "minHit": 2,
    "maxHit": 6,
    "def": 0,
    "exp": 55,
    "gold": 0
  },
  {
    "id": 76,
    "name": "Hormiga",
    "npcType": 0,
    "heading": 3,
    "body": 70,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 5,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 5,
    "gold": 0
  },
  {
    "id": 77,
    "name": "Rata",
    "npcType": 0,
    "heading": 3,
    "body": 71,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15,
    "minHit": 2,
    "maxHit": 4,
    "def": 0,
    "exp": 50,
    "gold": 0
  },
  {
    "id": 78,
    "name": "Oso pardo",
    "npcType": 0,
    "heading": 3,
    "body": 73,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 515,
    "minHit": 65,
    "maxHit": 100,
    "def": 0,
    "exp": 550,
    "gold": 0
  },
  {
    "id": 79,
    "name": "Tortuga gigante",
    "npcType": 0,
    "heading": 3,
    "body": 74,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 315,
    "minHit": 35,
    "maxHit": 80,
    "def": 0,
    "exp": 350,
    "gold": 0
  },
  {
    "id": 80,
    "name": "Vendedor General",
    "npcType": 0,
    "heading": 3,
    "body": 128,
    "head": 9,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 81,
    "name": "Sacerdote Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 101,
    "head": 4,
    "movement": 5,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 82,
    "name": "Sacerdote Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 101,
    "head": 5,
    "movement": 5,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 83,
    "name": "Druida Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 56,
    "head": 101,
    "movement": 5,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 84,
    "name": "Druida Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 56,
    "head": 102,
    "movement": 2,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 85,
    "name": "Druida Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 56,
    "head": 103,
    "movement": 2,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 86,
    "name": "Mago Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 130,
    "head": 6,
    "movement": 2,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 87,
    "name": "Mago Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 128,
    "head": 6,
    "movement": 2,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 88,
    "name": "Ely",
    "npcType": 0,
    "heading": 3,
    "body": 143,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 89,
    "name": "Fuego fatuo",
    "npcType": 0,
    "heading": 3,
    "body": 144,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 2500,
    "minHit": 80,
    "maxHit": 95,
    "def": 0,
    "exp": 1500,
    "gold": 300
  },
  {
    "id": 90,
    "name": "Alma de Morgolock",
    "npcType": 0,
    "heading": 3,
    "body": 144,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 29550,
    "minHit": 100,
    "maxHit": 100,
    "def": 0,
    "exp": 1000,
    "gold": 10000
  },
  {
    "id": 91,
    "name": "Gran Águila",
    "npcType": 0,
    "heading": 3,
    "body": 59,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 90,
    "minHit": 4,
    "maxHit": 15,
    "def": 0,
    "exp": 400,
    "gold": 0
  },
  {
    "id": 92,
    "name": "Elemental de agua",
    "npcType": 0,
    "heading": 3,
    "body": 154,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 360,
    "minHit": 60,
    "maxHit": 110,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 93,
    "name": "Elemental de fuego",
    "npcType": 0,
    "heading": 3,
    "body": 153,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 200,
    "minHit": 75,
    "maxHit": 40,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 94,
    "name": "Elemental de tierra",
    "npcType": 0,
    "heading": 3,
    "body": 152,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 200,
    "minHit": 30,
    "maxHit": 30,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 95,
    "name": "Jabalí",
    "npcType": 0,
    "heading": 3,
    "body": 150,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 515,
    "minHit": 65,
    "maxHit": 100,
    "def": 0,
    "exp": 600,
    "gold": 0
  },
  {
    "id": 96,
    "name": "Tigre",
    "npcType": 0,
    "heading": 3,
    "body": 147,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 800,
    "minHit": 30,
    "maxHit": 70,
    "def": 0,
    "exp": 120,
    "gold": 0
  },
  {
    "id": 97,
    "name": "Pato",
    "npcType": 0,
    "heading": 3,
    "body": 88,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 30,
    "minHit": 3,
    "maxHit": 5,
    "def": 0,
    "exp": 60,
    "gold": 0
  },
  {
    "id": 98,
    "name": "Demonio",
    "npcType": 5,
    "heading": 3,
    "body": 402,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 99,
    "name": "SastreNuevaEsperanza",
    "npcType": 0,
    "heading": 3,
    "body": 123,
    "head": 472,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 100,
    "name": "Guardia Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 15,
    "head": 0,
    "movement": 10,
    "agresivo": false,
    "hp": 1000,
    "minHit": 115,
    "maxHit": 250,
    "def": 30,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 101,
    "name": "Sacerdote Malvado",
    "npcType": 1,
    "heading": 3,
    "body": 135,
    "head": 401,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 102,
    "name": "SastreIlliandor",
    "npcType": 0,
    "heading": 3,
    "body": 331,
    "head": 471,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 103,
    "name": "ArmadurasEnanos",
    "npcType": 0,
    "heading": 3,
    "body": 110,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 104,
    "name": "MagoNuevaEsperanzaDruidas",
    "npcType": 0,
    "heading": 3,
    "body": 56,
    "head": 101,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 106,
    "name": "PirataBanderbill",
    "npcType": 7,
    "heading": 4,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 107,
    "name": "PirataNix",
    "npcType": 7,
    "heading": 3,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 108,
    "name": "PirataArghal",
    "npcType": 7,
    "heading": 4,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 109,
    "name": "PirataNuevaEsperanza",
    "npcType": 7,
    "heading": 2,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 110,
    "name": "Sacerdote del Caos",
    "npcType": 2,
    "heading": 3,
    "body": 140,
    "head": 203,
    "movement": 11,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 111,
    "name": "Mago del Caos",
    "npcType": 2,
    "heading": 3,
    "body": 35,
    "head": 205,
    "movement": 11,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 112,
    "name": "Galeón",
    "npcType": 0,
    "heading": 3,
    "body": 86,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 113,
    "name": "Propiedades Arghâl",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 114,
    "name": "Carcelero",
    "npcType": 0,
    "heading": 3,
    "body": 172,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 115,
    "name": "Propiedades Rinkel",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 116,
    "name": "PirataRinkel",
    "npcType": 7,
    "heading": 3,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 117,
    "name": "Cazarecompensas",
    "npcType": 10,
    "heading": 3,
    "body": 172,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 118,
    "name": "Propiedades Orac",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 119,
    "name": "Propiedades Suramei",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 120,
    "name": "Propiedades Illiandor",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 121,
    "name": "Veterinaria",
    "npcType": 11,
    "heading": 3,
    "body": 101,
    "head": 72,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 122,
    "name": "Herrero Armas Nix",
    "npcType": 0,
    "heading": 3,
    "body": 254,
    "head": 306,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 123,
    "name": "Herrero Armaduras Nix",
    "npcType": 0,
    "heading": 3,
    "body": 253,
    "head": 304,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 124,
    "name": "Herrero Armaduras Arghal",
    "npcType": 0,
    "heading": 3,
    "body": 22,
    "head": 14,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 125,
    "name": "Herrero Armas Arghal",
    "npcType": 0,
    "heading": 3,
    "body": 93,
    "head": 7,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 126,
    "name": "Fuego fatuo",
    "npcType": 0,
    "heading": 3,
    "body": 144,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 7,
    "minHit": 5,
    "maxHit": 10,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 127,
    "name": "Elemental de agua",
    "npcType": 0,
    "heading": 3,
    "body": 154,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 10,
    "minHit": 7,
    "maxHit": 20,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 128,
    "name": "Elemental de fuego",
    "npcType": 0,
    "heading": 3,
    "body": 153,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 10,
    "minHit": 5,
    "maxHit": 15,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 129,
    "name": "Elemental de tierra",
    "npcType": 0,
    "heading": 3,
    "body": 152,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 10,
    "minHit": 5,
    "maxHit": 15,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 130,
    "name": "Tigre",
    "npcType": 0,
    "heading": 3,
    "body": 147,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15,
    "minHit": 10,
    "maxHit": 20,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 131,
    "name": "Oso pardo",
    "npcType": 0,
    "heading": 3,
    "body": 73,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 20,
    "minHit": 5,
    "maxHit": 30,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 132,
    "name": "Ely",
    "npcType": 0,
    "heading": 3,
    "body": 143,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15,
    "minHit": 5,
    "maxHit": 20,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 133,
    "name": "Lobo",
    "npcType": 0,
    "heading": 3,
    "body": 10,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 20,
    "minHit": 10,
    "maxHit": 20,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 134,
    "name": "Torre Imperial",
    "npcType": 2,
    "heading": 3,
    "body": 238,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 200000,
    "minHit": 115,
    "maxHit": 250,
    "def": 30,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 135,
    "name": "Angel",
    "npcType": 0,
    "heading": 3,
    "body": 143,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 200,
    "minHit": 50,
    "maxHit": 25,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 136,
    "name": "Árbol",
    "npcType": 0,
    "heading": 3,
    "body": 26,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 1500,
    "minHit": 420,
    "maxHit": 250,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 137,
    "name": "Sirviente invisible",
    "npcType": 0,
    "heading": 3,
    "body": 26,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 50,
    "minHit": 120,
    "maxHit": 50,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 138,
    "name": "Guardia de la Milicia",
    "npcType": 2,
    "heading": 3,
    "body": 450,
    "head": 403,
    "movement": 12,
    "agresivo": false,
    "hp": 9550,
    "minHit": 100,
    "maxHit": 100,
    "def": 10,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 139,
    "name": "PirataTiama",
    "npcType": 7,
    "heading": 2,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 140,
    "name": "PirataOrac",
    "npcType": 7,
    "heading": 4,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 141,
    "name": "PirataIlliandor",
    "npcType": 7,
    "heading": 2,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 142,
    "name": "PirataLindos",
    "npcType": 7,
    "heading": 2,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 143,
    "name": "Pirata",
    "npcType": 7,
    "heading": 2,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 144,
    "name": "Timbero",
    "npcType": 12,
    "heading": 3,
    "body": 47,
    "head": 9,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 145,
    "name": "Ent",
    "npcType": 0,
    "heading": 3,
    "body": 273,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15,
    "minHit": 5,
    "maxHit": 20,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 146,
    "name": "Fuego fatuo",
    "npcType": 0,
    "heading": 3,
    "body": 144,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 600,
    "minHit": 75,
    "maxHit": 75,
    "def": 0,
    "exp": 0,
    "gold": 1
  },
  {
    "id": 147,
    "name": "Vendedor de Caballos",
    "npcType": 0,
    "heading": 3,
    "body": 133,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 148,
    "name": "Herrero Armas Tiama",
    "npcType": 0,
    "heading": 3,
    "body": 281,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 149,
    "name": "Herrero Armaduras Tiama",
    "npcType": 0,
    "heading": 3,
    "body": 93,
    "head": 6,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 150,
    "name": "Aleroy",
    "npcType": 13,
    "heading": 3,
    "body": 50,
    "head": 16,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 151,
    "name": "Markman",
    "npcType": 13,
    "heading": 3,
    "body": 4,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 152,
    "name": "Namatuflê",
    "npcType": 13,
    "heading": 3,
    "body": 214,
    "head": 175,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 153,
    "name": "Johnson",
    "npcType": 13,
    "heading": 3,
    "body": 256,
    "head": 207,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 154,
    "name": "MagoTiamaClerigos",
    "npcType": 0,
    "heading": 3,
    "body": 307,
    "head": 2,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 155,
    "name": "Ent",
    "npcType": 0,
    "heading": 3,
    "body": 273,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 300,
    "minHit": 60,
    "maxHit": 110,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 156,
    "name": "MagoArghalPaladines",
    "npcType": 0,
    "heading": 3,
    "body": 354,
    "head": 5,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 157,
    "name": "MagoIlliandorBardos",
    "npcType": 0,
    "heading": 3,
    "body": 22,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 158,
    "name": "Centinela",
    "npcType": 15,
    "heading": 3,
    "body": 214,
    "head": 175,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 159,
    "name": "Centinela",
    "npcType": 15,
    "heading": 3,
    "body": 86,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 160,
    "name": "Beholder Divino",
    "npcType": 14,
    "heading": 3,
    "body": 72,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 161,
    "name": "Ent Mágico",
    "npcType": 14,
    "heading": 3,
    "body": 273,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 162,
    "name": "Bruja Maligna",
    "npcType": 14,
    "heading": 3,
    "body": 125,
    "head": 271,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 163,
    "name": "Bardo",
    "npcType": 0,
    "heading": 3,
    "body": 17,
    "head": 0,
    "movement": 1,
    "agresivo": false,
    "hp": 315,
    "minHit": 35,
    "maxHit": 80,
    "def": 0,
    "exp": 320,
    "gold": 0
  },
  {
    "id": 164,
    "name": "Subastador",
    "npcType": 16,
    "heading": 3,
    "body": 270,
    "head": 9,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 165,
    "name": "Guardia del vaticano",
    "npcType": 0,
    "heading": 3,
    "body": 265,
    "head": 12,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 166,
    "name": "Rivald Orac",
    "npcType": 0,
    "heading": 3,
    "body": 128,
    "head": 11,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 167,
    "name": "SastreSuramei",
    "npcType": 0,
    "heading": 3,
    "body": 356,
    "head": 402,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 168,
    "name": "Propiedades Tiama",
    "npcType": 0,
    "heading": 3,
    "body": 1,
    "head": 4,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 169,
    "name": "Lobo Invernal",
    "npcType": 0,
    "heading": 3,
    "body": 284,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 20,
    "minHit": 10,
    "maxHit": 20,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 170,
    "name": "Malvor",
    "npcType": 13,
    "heading": 3,
    "body": 100,
    "head": 301,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 171,
    "name": "Demedor Falentus",
    "npcType": 18,
    "heading": 3,
    "body": 57,
    "head": 9,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 172,
    "name": "Barinke Fauster",
    "npcType": 5,
    "heading": 3,
    "body": 106,
    "head": 5,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 173,
    "name": "Halinte Ganre",
    "npcType": 18,
    "heading": 3,
    "body": 355,
    "head": 12,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 174,
    "name": "Enlistador de Piratas",
    "npcType": 5,
    "heading": 3,
    "body": 22,
    "head": 17,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 175,
    "name": "Enlistador de Corsarios del Imperio",
    "npcType": 5,
    "heading": 3,
    "body": 142,
    "head": 72,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 176,
    "name": "Enlistador de Corsarios de la República",
    "npcType": 5,
    "heading": 3,
    "body": 254,
    "head": 409,
    "movement": 1,
    "agresivo": false,
    "hp": 0,
    "minHit": 0,
    "maxHit": 0,
    "def": 0,
    "exp": 0,
    "gold": 0
  },
  {
    "id": 500,
    "name": "Murciélago",
    "npcType": 0,
    "heading": 3,
    "body": 9,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 15,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 20,
    "gold": 2
  },
  {
    "id": 501,
    "name": "Lobo",
    "npcType": 0,
    "heading": 3,
    "body": 10,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 75,
    "minHit": 12,
    "maxHit": 18,
    "def": 8,
    "exp": 115,
    "gold": 3
  },
  {
    "id": 502,
    "name": "Zombie",
    "npcType": 0,
    "heading": 3,
    "body": 11,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 320,
    "minHit": 25,
    "maxHit": 30,
    "def": 20,
    "exp": 295,
    "gold": 45
  },
  {
    "id": 503,
    "name": "Esqueleto",
    "npcType": 0,
    "heading": 3,
    "body": 12,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 50,
    "minHit": 3,
    "maxHit": 9,
    "def": 10,
    "exp": 66,
    "gold": 10
  },
  {
    "id": 504,
    "name": "Serpiente",
    "npcType": 0,
    "heading": 3,
    "body": 13,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 18,
    "minHit": 2,
    "maxHit": 3,
    "def": 0,
    "exp": 25,
    "gold": 0
  },
  {
    "id": 505,
    "name": "Goblin",
    "npcType": 0,
    "heading": 3,
    "body": 14,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 110,
    "minHit": 15,
    "maxHit": 20,
    "def": 15,
    "exp": 160,
    "gold": 35
  },
  {
    "id": 506,
    "name": "Gallo Salvaje",
    "npcType": 0,
    "heading": 3,
    "body": 5,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 10,
    "minHit": 1,
    "maxHit": 2,
    "def": 0,
    "exp": 16,
    "gold": 1
  },
  {
    "id": 507,
    "name": "Lord Zombie",
    "npcType": 0,
    "heading": 3,
    "body": 11,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 430,
    "minHit": 55,
    "maxHit": 65,
    "def": 35,
    "exp": 460,
    "gold": 70
  },
  {
    "id": 508,
    "name": "Esqueleto Guerrero",
    "npcType": 0,
    "heading": 3,
    "body": 12,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 200,
    "minHit": 20,
    "maxHit": 25,
    "def": 19,
    "exp": 270,
    "gold": 30
  },
  {
    "id": 509,
    "name": "Draco",
    "npcType": 6,
    "heading": 3,
    "body": 362,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 2700,
    "minHit": 260,
    "maxHit": 290,
    "def": 50,
    "exp": 4000,
    "gold": 2000
  },
  {
    "id": 510,
    "name": "Araña Gigante",
    "npcType": 0,
    "heading": 3,
    "body": 42,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 950,
    "minHit": 70,
    "maxHit": 115,
    "def": 0,
    "exp": 1450,
    "gold": 380
  },
  {
    "id": 511,
    "name": "Dragón Legendario",
    "npcType": 6,
    "heading": 3,
    "body": 361,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 650000,
    "minHit": 400,
    "maxHit": 500,
    "def": 0,
    "exp": 1000000,
    "gold": 105000
  },
  {
    "id": 512,
    "name": "Hechicero de Fuego",
    "npcType": 6,
    "heading": 3,
    "body": 1,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 28000,
    "minHit": 200,
    "maxHit": 300,
    "def": 0,
    "exp": 25000,
    "gold": 65000
  },
  {
    "id": 513,
    "name": "Zombie",
    "npcType": 0,
    "heading": 3,
    "body": 11,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 250,
    "minHit": 4,
    "maxHit": 12,
    "def": 35,
    "exp": 241,
    "gold": 30
  },
  {
    "id": 514,
    "name": "Esqueleto",
    "npcType": 0,
    "heading": 3,
    "body": 12,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 30,
    "minHit": 1,
    "maxHit": 8,
    "def": 10,
    "exp": 51,
    "gold": 6
  },
  {
    "id": 515,
    "name": "Serpiente",
    "npcType": 0,
    "heading": 3,
    "body": 13,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 22,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 18,
    "gold": 2
  },
  {
    "id": 516,
    "name": "Goblin",
    "npcType": 0,
    "heading": 3,
    "body": 14,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 110,
    "minHit": 4,
    "maxHit": 12,
    "def": 15,
    "exp": 112,
    "gold": 0
  },
  {
    "id": 517,
    "name": "Gallo Salvaje",
    "npcType": 0,
    "heading": 3,
    "body": 5,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 15,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 17,
    "gold": 1
  },
  {
    "id": 518,
    "name": "Lord Zombie",
    "npcType": 0,
    "heading": 3,
    "body": 11,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 350,
    "minHit": 10,
    "maxHit": 25,
    "def": 35,
    "exp": 391,
    "gold": 51
  },
  {
    "id": 519,
    "name": "Esqueleto Guerrero",
    "npcType": 0,
    "heading": 3,
    "body": 12,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 150,
    "minHit": 8,
    "maxHit": 18,
    "def": 19,
    "exp": 187,
    "gold": 20
  },
  {
    "id": 520,
    "name": "Dragon Rojo",
    "npcType": 0,
    "heading": 3,
    "body": 358,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 3000,
    "minHit": 250,
    "maxHit": 300,
    "def": 20,
    "exp": 4000,
    "gold": 2000
  },
  {
    "id": 521,
    "name": "Araña Gigante",
    "npcType": 0,
    "heading": 3,
    "body": 42,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1200,
    "minHit": 75,
    "maxHit": 120,
    "def": 0,
    "exp": 2420,
    "gold": 210
  },
  {
    "id": 522,
    "name": "Orco",
    "npcType": 0,
    "heading": 3,
    "body": 43,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 350,
    "minHit": 5,
    "maxHit": 30,
    "def": 30,
    "exp": 505,
    "gold": 59
  },
  {
    "id": 523,
    "name": "Orco",
    "npcType": 0,
    "heading": 3,
    "body": 43,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 320,
    "minHit": 15,
    "maxHit": 38,
    "def": 30,
    "exp": 505,
    "gold": 65
  },
  {
    "id": 524,
    "name": "Jefe Orco",
    "npcType": 0,
    "heading": 3,
    "body": 43,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 600,
    "minHit": 75,
    "maxHit": 400,
    "def": 30,
    "exp": 680,
    "gold": 200
  },
  {
    "id": 525,
    "name": "Águila",
    "npcType": 0,
    "heading": 3,
    "body": 9,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 20,
    "minHit": 2,
    "maxHit": 3,
    "def": 0,
    "exp": 18,
    "gold": 5
  },
  {
    "id": 526,
    "name": "Araña Gigante",
    "npcType": 0,
    "heading": 3,
    "body": 42,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 2000,
    "minHit": 75,
    "maxHit": 100,
    "def": 10,
    "exp": 4861,
    "gold": 420
  },
  {
    "id": 527,
    "name": "Dragon Rojo",
    "npcType": 0,
    "heading": 3,
    "body": 358,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 4500,
    "minHit": 250,
    "maxHit": 300,
    "def": 20,
    "exp": 6000,
    "gold": 2500
  },
  {
    "id": 528,
    "name": "Araña Gigante",
    "npcType": 0,
    "heading": 3,
    "body": 42,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1200,
    "minHit": 75,
    "maxHit": 100,
    "def": 20,
    "exp": 2150,
    "gold": 450
  },
  {
    "id": 529,
    "name": "Escorpión",
    "npcType": 0,
    "heading": 3,
    "body": 51,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 32,
    "minHit": 3,
    "maxHit": 6,
    "def": 0,
    "exp": 40,
    "gold": 4
  },
  {
    "id": 530,
    "name": "Bandido",
    "npcType": 0,
    "heading": 3,
    "body": 47,
    "head": 2,
    "movement": 3,
    "agresivo": true,
    "hp": 350,
    "minHit": 36,
    "maxHit": 60,
    "def": 0,
    "exp": 760,
    "gold": 270
  },
  {
    "id": 531,
    "name": "Asesino",
    "npcType": 0,
    "heading": 3,
    "body": 48,
    "head": 201,
    "movement": 3,
    "agresivo": true,
    "hp": 700,
    "minHit": 40,
    "maxHit": 130,
    "def": 0,
    "exp": 1750,
    "gold": 560
  },
  {
    "id": 532,
    "name": "Águila",
    "npcType": 0,
    "heading": 3,
    "body": 59,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 20,
    "minHit": 3,
    "maxHit": 2,
    "def": 0,
    "exp": 18,
    "gold": 5
  },
  {
    "id": 533,
    "name": "Cuervo",
    "npcType": 0,
    "heading": 3,
    "body": 68,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 30,
    "minHit": 4,
    "maxHit": 10,
    "def": 0,
    "exp": 53,
    "gold": 5
  },
  {
    "id": 534,
    "name": "Señor de las sombras",
    "npcType": 0,
    "heading": 3,
    "body": 69,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 400,
    "minHit": 60,
    "maxHit": 75,
    "def": 0,
    "exp": 550,
    "gold": 25
  },
  {
    "id": 535,
    "name": "Hormiga",
    "npcType": 0,
    "heading": 3,
    "body": 70,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 5,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 6,
    "gold": 0
  },
  {
    "id": 536,
    "name": "Rata Gigante",
    "npcType": 0,
    "heading": 3,
    "body": 71,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 15,
    "minHit": 2,
    "maxHit": 4,
    "def": 0,
    "exp": 21,
    "gold": 2
  },
  {
    "id": 537,
    "name": "Beholder",
    "npcType": 0,
    "heading": 3,
    "body": 72,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1100,
    "minHit": 65,
    "maxHit": 290,
    "def": 0,
    "exp": 2020,
    "gold": 415
  },
  {
    "id": 538,
    "name": "Oso Pardo",
    "npcType": 0,
    "heading": 3,
    "body": 73,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 920,
    "minHit": 100,
    "maxHit": 135,
    "def": 0,
    "exp": 1350,
    "gold": 0
  },
  {
    "id": 539,
    "name": "Tortuga Gigante",
    "npcType": 0,
    "heading": 3,
    "body": 74,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 480,
    "minHit": 60,
    "maxHit": 80,
    "def": 10,
    "exp": 550,
    "gold": 0
  },
  {
    "id": 540,
    "name": "Duende",
    "npcType": 0,
    "heading": 3,
    "body": 75,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 210,
    "minHit": 25,
    "maxHit": 35,
    "def": 0,
    "exp": 268,
    "gold": 40
  },
  {
    "id": 541,
    "name": "Ogro",
    "npcType": 0,
    "heading": 3,
    "body": 76,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 2200,
    "minHit": 130,
    "maxHit": 145,
    "def": 20,
    "exp": 2900,
    "gold": 700
  },
  {
    "id": 542,
    "name": "Gran Dragón Negro",
    "npcType": 6,
    "heading": 3,
    "body": 362,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 380000,
    "minHit": 1300,
    "maxHit": 2400,
    "def": 0,
    "exp": 450000,
    "gold": 85000
  },
  {
    "id": 543,
    "name": "Demonio",
    "npcType": 9,
    "heading": 3,
    "body": 365,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 15000,
    "minHit": 110,
    "maxHit": 270,
    "def": 20,
    "exp": 40000,
    "gold": 10000
  },
  {
    "id": 544,
    "name": "Lobo",
    "npcType": 0,
    "heading": 3,
    "body": 10,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 75,
    "minHit": 1,
    "maxHit": 18,
    "def": 8,
    "exp": 118,
    "gold": 3
  },
  {
    "id": 545,
    "name": "Lobo",
    "npcType": 0,
    "heading": 3,
    "body": 10,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 300,
    "minHit": 12,
    "maxHit": 20,
    "def": 30,
    "exp": 230,
    "gold": 4
  },
  {
    "id": 546,
    "name": "Zombie",
    "npcType": 0,
    "heading": 3,
    "body": 11,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 350,
    "minHit": 40,
    "maxHit": 50,
    "def": 30,
    "exp": 230,
    "gold": 0
  },
  {
    "id": 547,
    "name": "Draco",
    "npcType": 6,
    "heading": 3,
    "body": 362,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 35000,
    "minHit": 1000,
    "maxHit": 5000,
    "def": 0,
    "exp": 85000,
    "gold": 9000
  },
  {
    "id": 548,
    "name": "Leviatán",
    "npcType": 0,
    "heading": 3,
    "body": 99,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 7000,
    "minHit": 80,
    "maxHit": 250,
    "def": 0,
    "exp": 20000,
    "gold": 5000
  },
  {
    "id": 549,
    "name": "Orco brujo",
    "npcType": 0,
    "heading": 3,
    "body": 43,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1200,
    "minHit": 75,
    "maxHit": 250,
    "def": 25,
    "exp": 3000,
    "gold": 1000
  },
  {
    "id": 550,
    "name": "Bruja",
    "npcType": 0,
    "heading": 3,
    "body": 125,
    "head": 271,
    "movement": 3,
    "agresivo": true,
    "hp": 4200,
    "minHit": 75,
    "maxHit": 140,
    "def": 20,
    "exp": 10000,
    "gold": 3500
  },
  {
    "id": 551,
    "name": "Mago protector",
    "npcType": 0,
    "heading": 3,
    "body": 135,
    "head": 401,
    "movement": 3,
    "agresivo": true,
    "hp": 2600,
    "minHit": 75,
    "maxHit": 126,
    "def": 20,
    "exp": 6000,
    "gold": 3000
  },
  {
    "id": 552,
    "name": "Golem de piedra",
    "npcType": 0,
    "heading": 3,
    "body": 371,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 46500,
    "minHit": 300,
    "maxHit": 480,
    "def": 40,
    "exp": 80000,
    "gold": 24000
  },
  {
    "id": 553,
    "name": "Medusa",
    "npcType": 0,
    "heading": 3,
    "body": 367,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 6000,
    "minHit": 95,
    "maxHit": 140,
    "def": 30,
    "exp": 20000,
    "gold": 6500
  },
  {
    "id": 554,
    "name": "Liche",
    "npcType": 0,
    "heading": 3,
    "body": 149,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1600,
    "minHit": 120,
    "maxHit": 250,
    "def": 30,
    "exp": 3500,
    "gold": 1300
  },
  {
    "id": 555,
    "name": "Lord Orco",
    "npcType": 0,
    "heading": 3,
    "body": 148,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1420,
    "minHit": 200,
    "maxHit": 200,
    "def": 30,
    "exp": 3200,
    "gold": 1600
  },
  {
    "id": 556,
    "name": "Quark",
    "npcType": 0,
    "heading": 3,
    "body": 146,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 30,
    "minHit": 4,
    "maxHit": 10,
    "def": 30,
    "exp": 65,
    "gold": 25
  },
  {
    "id": 557,
    "name": "Jabalí Salvaje",
    "npcType": 0,
    "heading": 3,
    "body": 150,
    "head": 0,
    "movement": 2,
    "agresivo": true,
    "hp": 515,
    "minHit": 65,
    "maxHit": 100,
    "def": 0,
    "exp": 442,
    "gold": 0
  },
  {
    "id": 558,
    "name": "Dark MaRcHaO",
    "npcType": 0,
    "heading": 3,
    "body": 56,
    "head": 101,
    "movement": 10,
    "agresivo": true,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 30,
    "exp": 80000,
    "gold": 30000
  },
  {
    "id": 559,
    "name": "Dark XoGo",
    "npcType": 0,
    "heading": 3,
    "body": 93,
    "head": 102,
    "movement": 3,
    "agresivo": true,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 30,
    "exp": 80000,
    "gold": 30000
  },
  {
    "id": 560,
    "name": "Dark Barrin",
    "npcType": 0,
    "heading": 3,
    "body": 94,
    "head": 202,
    "movement": 3,
    "agresivo": false,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 30,
    "exp": 80000,
    "gold": 30000
  },
  {
    "id": 561,
    "name": "Saqueador de minas",
    "npcType": 0,
    "heading": 3,
    "body": 136,
    "head": 401,
    "movement": 3,
    "agresivo": true,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 30,
    "exp": 60000,
    "gold": 25000
  },
  {
    "id": 562,
    "name": "Dark Ruthnar",
    "npcType": 0,
    "heading": 3,
    "body": 63,
    "head": 11,
    "movement": 3,
    "agresivo": false,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 30,
    "exp": 80000,
    "gold": 30000
  },
  {
    "id": 563,
    "name": "Goblin",
    "npcType": 0,
    "heading": 3,
    "body": 14,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 110,
    "minHit": 5,
    "maxHit": 12,
    "def": 15,
    "exp": 130,
    "gold": 0
  },
  {
    "id": 564,
    "name": "Escorpion",
    "npcType": 0,
    "heading": 3,
    "body": 51,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 32,
    "minHit": 1,
    "maxHit": 3,
    "def": 0,
    "exp": 38,
    "gold": 0
  },
  {
    "id": 565,
    "name": "Serpiente",
    "npcType": 0,
    "heading": 3,
    "body": 13,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 20,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 20,
    "gold": 0
  },
  {
    "id": 566,
    "name": "Murcielago",
    "npcType": 0,
    "heading": 3,
    "body": 9,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 10,
    "minHit": 1,
    "maxHit": 1,
    "def": 0,
    "exp": 15,
    "gold": 2
  },
  {
    "id": 567,
    "name": "Arquero Pirata",
    "npcType": 0,
    "heading": 3,
    "body": 110,
    "head": 301,
    "movement": 3,
    "agresivo": true,
    "hp": 9000,
    "minHit": 45,
    "maxHit": 275,
    "def": 30,
    "exp": 17000,
    "gold": 2000
  },
  {
    "id": 568,
    "name": "Guerrero Pirata",
    "npcType": 0,
    "heading": 3,
    "body": 110,
    "head": 301,
    "movement": 3,
    "agresivo": true,
    "hp": 15000,
    "minHit": 90,
    "maxHit": 300,
    "def": 30,
    "exp": 28000,
    "gold": 8500
  },
  {
    "id": 569,
    "name": "Fuego Fatuo",
    "npcType": 0,
    "heading": 3,
    "body": 144,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 15000,
    "minHit": 100,
    "maxHit": 100,
    "def": 0,
    "exp": 35000,
    "gold": 0
  },
  {
    "id": 570,
    "name": "Gran Dragón Verde",
    "npcType": 6,
    "heading": 3,
    "body": 360,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 50000,
    "minHit": 500,
    "maxHit": 600,
    "def": 0,
    "exp": 80000,
    "gold": 20000
  },
  {
    "id": 571,
    "name": "Fango",
    "npcType": 0,
    "heading": 3,
    "body": 173,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1900,
    "minHit": 80,
    "maxHit": 110,
    "def": 0,
    "exp": 3800,
    "gold": 600
  },
  {
    "id": 572,
    "name": "Demonio Abisal",
    "npcType": 9,
    "heading": 3,
    "body": 363,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 40000,
    "minHit": 200,
    "maxHit": 250,
    "def": 30,
    "exp": 78000,
    "gold": 20000
  },
  {
    "id": 573,
    "name": "Basilisco",
    "npcType": 0,
    "heading": 3,
    "body": 167,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1100,
    "minHit": 20,
    "maxHit": 150,
    "def": 0,
    "exp": 2600,
    "gold": 800
  },
  {
    "id": 574,
    "name": "Ogro Guerrero",
    "npcType": 0,
    "heading": 3,
    "body": 237,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 2800,
    "minHit": 130,
    "maxHit": 285,
    "def": 30,
    "exp": 6400,
    "gold": 950
  },
  {
    "id": 575,
    "name": "Golem de oro",
    "npcType": 0,
    "heading": 3,
    "body": 373,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 100000,
    "minHit": 400,
    "maxHit": 510,
    "def": 60,
    "exp": 150000,
    "gold": 50000
  },
  {
    "id": 576,
    "name": "Momia",
    "npcType": 0,
    "heading": 3,
    "body": 369,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 8000,
    "minHit": 50,
    "maxHit": 200,
    "def": 0,
    "exp": 19000,
    "gold": 6000
  },
  {
    "id": 577,
    "name": "Golem de bronce",
    "npcType": 0,
    "heading": 3,
    "body": 373,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 30000,
    "minHit": 120,
    "maxHit": 210,
    "def": 30,
    "exp": 45000,
    "gold": 15000
  },
  {
    "id": 578,
    "name": "Medusa Matriarch",
    "npcType": 0,
    "heading": 3,
    "body": 368,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 21000,
    "minHit": 110,
    "maxHit": 160,
    "def": 30,
    "exp": 56000,
    "gold": 14000
  },
  {
    "id": 579,
    "name": "Golem de plata",
    "npcType": 0,
    "heading": 3,
    "body": 375,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 72000,
    "minHit": 400,
    "maxHit": 490,
    "def": 30,
    "exp": 110000,
    "gold": 20000
  },
  {
    "id": 580,
    "name": "Lobo Invernal",
    "npcType": 0,
    "heading": 3,
    "body": 284,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 225,
    "minHit": 15,
    "maxHit": 40,
    "def": 12,
    "exp": 560,
    "gold": 150
  },
  {
    "id": 581,
    "name": "Golem infernal",
    "npcType": 0,
    "heading": 3,
    "body": 374,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 150000,
    "minHit": 440,
    "maxHit": 530,
    "def": 64,
    "exp": 200000,
    "gold": 60000
  },
  {
    "id": 582,
    "name": "Gran Dragón Azul",
    "npcType": 6,
    "heading": 3,
    "body": 359,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 140000,
    "minHit": 700,
    "maxHit": 1200,
    "def": 0,
    "exp": 280000,
    "gold": 60000
  },
  {
    "id": 583,
    "name": "Esqueleto Guerrero",
    "npcType": 0,
    "heading": 3,
    "body": 171,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 330,
    "minHit": 60,
    "maxHit": 70,
    "def": 19,
    "exp": 500,
    "gold": 220
  },
  {
    "id": 584,
    "name": "Cíclope",
    "npcType": 0,
    "heading": 3,
    "body": 166,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1900,
    "minHit": 50,
    "maxHit": 130,
    "def": 0,
    "exp": 3300,
    "gold": 1300
  },
  {
    "id": 585,
    "name": "Yeti",
    "npcType": 0,
    "heading": 3,
    "body": 370,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 65000,
    "minHit": 460,
    "maxHit": 550,
    "def": 25,
    "exp": 195000,
    "gold": 30000
  },
  {
    "id": 586,
    "name": "Aparición",
    "npcType": 0,
    "heading": 3,
    "body": 245,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 3500,
    "minHit": 40,
    "maxHit": 80,
    "def": 20,
    "exp": 8000,
    "gold": 2400
  },
  {
    "id": 587,
    "name": "Golem de hielo",
    "npcType": 0,
    "heading": 3,
    "body": 377,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 175000,
    "minHit": 450,
    "maxHit": 540,
    "def": 60,
    "exp": 260000,
    "gold": 80000
  },
  {
    "id": 588,
    "name": "Crako",
    "npcType": 0,
    "heading": 3,
    "body": 219,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 4000,
    "minHit": 150,
    "maxHit": 380,
    "def": 0,
    "exp": 10500,
    "gold": 3000
  },
  {
    "id": 589,
    "name": "Protector",
    "npcType": 0,
    "heading": 3,
    "body": 172,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 1000,
    "minHit": 80,
    "maxHit": 120,
    "def": 0,
    "exp": 2500,
    "gold": 500
  },
  {
    "id": 590,
    "name": "Rey Dragón",
    "npcType": 6,
    "heading": 3,
    "body": 357,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 900000,
    "minHit": 3000,
    "maxHit": 6100,
    "def": 50,
    "exp": 2200000,
    "gold": 360000
  },
  {
    "id": 591,
    "name": "Dark Greco",
    "npcType": 0,
    "heading": 3,
    "body": 161,
    "head": 6,
    "movement": 3,
    "agresivo": true,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 10,
    "exp": 110000,
    "gold": 30000
  },
  {
    "id": 592,
    "name": "Ent",
    "npcType": 0,
    "heading": 3,
    "body": 273,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 650,
    "minHit": 40,
    "maxHit": 90,
    "def": 30,
    "exp": 1200,
    "gold": 200
  },
  {
    "id": 593,
    "name": "Gladiador",
    "npcType": 0,
    "heading": 3,
    "body": 364,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 3000,
    "minHit": 120,
    "maxHit": 282,
    "def": 10,
    "exp": 7000,
    "gold": 1500
  },
  {
    "id": 594,
    "name": "Gallina Salvaje",
    "npcType": 0,
    "heading": 3,
    "body": 278,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 27,
    "minHit": 1,
    "maxHit": 2,
    "def": 0,
    "exp": 28,
    "gold": 3
  },
  {
    "id": 595,
    "name": "Sirena",
    "npcType": 0,
    "heading": 3,
    "body": 277,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 8000,
    "minHit": 80,
    "maxHit": 250,
    "def": 25,
    "exp": 23500,
    "gold": 5000
  },
  {
    "id": 596,
    "name": "Demonio Ryghar",
    "npcType": 9,
    "heading": 3,
    "body": 284,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 40000,
    "minHit": 150,
    "maxHit": 250,
    "def": 0,
    "exp": 80000,
    "gold": 25000
  },
  {
    "id": 597,
    "name": "Rey Dragón",
    "npcType": 6,
    "heading": 3,
    "body": 357,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 350000,
    "minHit": 3000,
    "maxHit": 6100,
    "def": 50,
    "exp": 1000000,
    "gold": 150000
  },
  {
    "id": 598,
    "name": "Vaca",
    "npcType": 0,
    "heading": 3,
    "body": 366,
    "head": 0,
    "movement": 2,
    "agresivo": false,
    "hp": 45,
    "minHit": 1,
    "maxHit": 3,
    "def": 2,
    "exp": 20,
    "gold": 0
  },
  {
    "id": 600,
    "name": "Golem protector del Fuego",
    "npcType": 0,
    "heading": 3,
    "body": 374,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 80000,
    "minHit": 440,
    "maxHit": 530,
    "def": 30,
    "exp": 250000,
    "gold": 0
  },
  {
    "id": 601,
    "name": "Golem protector del Aire",
    "npcType": 0,
    "heading": 3,
    "body": 375,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 80000,
    "minHit": 400,
    "maxHit": 490,
    "def": 30,
    "exp": 250000,
    "gold": 0
  },
  {
    "id": 602,
    "name": "Dark PleXus",
    "npcType": 0,
    "heading": 3,
    "body": 338,
    "head": 106,
    "movement": 3,
    "agresivo": false,
    "hp": 45000,
    "minHit": 50,
    "maxHit": 400,
    "def": 30,
    "exp": 80000,
    "gold": 30000
  },
  {
    "id": 603,
    "name": "Chamán Ártico",
    "npcType": 0,
    "heading": 3,
    "body": 418,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 3500,
    "minHit": 110,
    "maxHit": 150,
    "def": 15,
    "exp": 6800,
    "gold": 1500
  },
  {
    "id": 604,
    "name": "Yuan Ti",
    "npcType": 0,
    "heading": 3,
    "body": 417,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 2500,
    "minHit": 130,
    "maxHit": 160,
    "def": 15,
    "exp": 4600,
    "gold": 1100
  },
  {
    "id": 605,
    "name": "Huargo de Nieve",
    "npcType": 0,
    "heading": 3,
    "body": 414,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 800,
    "minHit": 110,
    "maxHit": 120,
    "def": 10,
    "exp": 1070,
    "gold": 200
  },
  {
    "id": 606,
    "name": "Hombre Lagarto",
    "npcType": 0,
    "heading": 3,
    "body": 445,
    "head": 0,
    "movement": 3,
    "agresivo": true,
    "hp": 4000,
    "minHit": 140,
    "maxHit": 250,
    "def": 30,
    "exp": 8600,
    "gold": 1900
  },
  {
    "id": 610,
    "name": "Hechicero de Agua",
    "npcType": 6,
    "heading": 3,
    "body": 442,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 28000,
    "minHit": 200,
    "maxHit": 300,
    "def": 0,
    "exp": 25000,
    "gold": 65000
  },
  {
    "id": 611,
    "name": "Hechicero de Viento",
    "npcType": 6,
    "heading": 3,
    "body": 443,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 28000,
    "minHit": 200,
    "maxHit": 300,
    "def": 0,
    "exp": 25000,
    "gold": 65000
  },
  {
    "id": 612,
    "name": "Hechicero de Tierra",
    "npcType": 6,
    "heading": 3,
    "body": 444,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 28000,
    "minHit": 200,
    "maxHit": 300,
    "def": 0,
    "exp": 25000,
    "gold": 65000
  },
  {
    "id": 613,
    "name": "Profeta Arcano",
    "npcType": 6,
    "heading": 3,
    "body": 474,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 60000,
    "minHit": 200,
    "maxHit": 300,
    "def": 0,
    "exp": 45000,
    "gold": 75000
  },
  {
    "id": 614,
    "name": "Gran Hechicero Garveloth",
    "npcType": 6,
    "heading": 3,
    "body": 480,
    "head": 0,
    "movement": 10,
    "agresivo": true,
    "hp": 150000,
    "minHit": 250,
    "maxHit": 300,
    "def": 0,
    "exp": 43000,
    "gold": 43000
  }
];
