export const IMPORTED_SPELLS = [
  {
    "id": 1,
    "nombre": "Curar veneno",
    "desc": "Cura el envenenamiento",
    "palabrasMagicas": "Nihil Ved",
    "manaRequerido": 10,
    "staRequerido": 1,
    "minSkill": 8,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 239,
    "fx": 2
  },
  {
    "id": 2,
    "nombre": "Proyectil mágico",
    "desc": "Causa 2 a 7 puntos daño a la víctima.",
    "palabrasMagicas": "Rah'Za'Lu",
    "manaRequerido": 12,
    "staRequerido": 2,
    "minSkill": 5,
    "tipo": 1,
    "target": 3,
    "minHP": 2,
    "maxHP": 7,
    "wav": 233,
    "fx": 9
  },
  {
    "id": 3,
    "nombre": "Curar heridas leves",
    "desc": "Curar heridas leves, restaura entre 1 y 5 puntos de salud.",
    "palabrasMagicas": "Corp Sanc",
    "manaRequerido": 10,
    "staRequerido": 3,
    "minSkill": 10,
    "tipo": 1,
    "target": 3,
    "minHP": 1,
    "maxHP": 5,
    "wav": 238,
    "fx": 0
  },
  {
    "id": 4,
    "nombre": "Envenenar",
    "desc": "Envenenamiento, provoca la muerte si no se contraresta con un antídoto.",
    "palabrasMagicas": "SERP XON IN",
    "manaRequerido": 20,
    "staRequerido": 4,
    "minSkill": 20,
    "tipo": 2,
    "target": 3,
    "minHP": 0,
    "maxHP": 0,
    "wav": 16,
    "fx": 32
  },
  {
    "id": 5,
    "nombre": "Curar heridas graves",
    "desc": "Curar heridas graves, restaura entre 15 y 25 puntos de salud.",
    "palabrasMagicas": "EN CORP SANCTIS",
    "manaRequerido": 40,
    "staRequerido": 5,
    "minSkill": 35,
    "tipo": 1,
    "target": 3,
    "minHP": 15,
    "maxHP": 25,
    "wav": 240,
    "fx": 9
  },
  {
    "id": 6,
    "nombre": "Saeta Ígnea",
    "desc": "Causa 7 a 14 puntos de daño a la victima.",
    "palabrasMagicas": "Fogûs Saex",
    "manaRequerido": 20,
    "staRequerido": 5,
    "minSkill": 12,
    "tipo": 1,
    "target": 3,
    "minHP": 7,
    "maxHP": 14,
    "wav": 19,
    "fx": 0
  },
  {
    "id": 7,
    "nombre": "Proyectil eléctrico",
    "desc": "Causa 14 a 22 puntos de daño a la victima.",
    "palabrasMagicas": "SUN VAP",
    "manaRequerido": 35,
    "staRequerido": 7,
    "minSkill": 22,
    "tipo": 1,
    "target": 3,
    "minHP": 14,
    "maxHP": 22,
    "wav": 16,
    "fx": 25
  },
  {
    "id": 8,
    "nombre": "Bomba mágica",
    "desc": "Causa 10 a 30 puntos de daño en un área de dos tiles.",
    "palabrasMagicas": "VAX IN TAR",
    "manaRequerido": 50,
    "staRequerido": 20,
    "minSkill": 38,
    "tipo": 1,
    "target": 4,
    "minHP": 5,
    "maxHP": 5,
    "wav": 129,
    "fx": 50
  },
  {
    "id": 9,
    "nombre": "Paralizar",
    "desc": "Impide que la víctima realize todo movimiento.",
    "palabrasMagicas": "HOAX VORP",
    "manaRequerido": 350,
    "staRequerido": 90,
    "minSkill": 60,
    "tipo": 2,
    "target": 3,
    "minHP": 0,
    "maxHP": 0,
    "wav": 203,
    "fx": 8
  },
  {
    "id": 10,
    "nombre": "Remover paralisis",
    "desc": "Remueve la paralisis.",
    "palabrasMagicas": "AN HOAX VORP",
    "manaRequerido": 300,
    "staRequerido": 80,
    "minSkill": 45,
    "tipo": 2,
    "target": 3,
    "minHP": 0,
    "maxHP": 0,
    "wav": 255,
    "fx": 0
  },
  {
    "id": 11,
    "nombre": "Resucitar",
    "desc": "Resucitar un usuario muerto.",
    "palabrasMagicas": "AHIL KNÄ XÄR",
    "manaRequerido": 420,
    "staRequerido": 100,
    "minSkill": 75,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 20,
    "fx": 0
  },
  {
    "id": 12,
    "nombre": "Grito de Igôr",
    "desc": "Aumenta criticamente la fuerza.",
    "palabrasMagicas": "ÔL HÀX",
    "manaRequerido": 360,
    "staRequerido": 40,
    "minSkill": 55,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 92,
    "fx": 0
  },
  {
    "id": 13,
    "nombre": "Furia de Uhkrul",
    "desc": "Furia de Uhkrul, aumenta la fuerza y la agilidad del objetivo criticamente.",
    "palabrasMagicas": "ÛX'ÔL'HIC",
    "manaRequerido": 720,
    "staRequerido": 250,
    "minSkill": 85,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 30,
    "fx": 29
  },
  {
    "id": 14,
    "nombre": "Invisibilidad",
    "desc": "Vuelve invisible al objetivo, efecto no permanente.",
    "palabrasMagicas": "",
    "manaRequerido": 560,
    "staRequerido": 60,
    "minSkill": 87,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 123,
    "fx": 46
  },
  {
    "id": 15,
    "nombre": "Tormenta de fuego",
    "desc": "Causa 15 a 50 puntos de daño en un área de tres tiles.",
    "palabrasMagicas": "RAX IN ZAR",
    "manaRequerido": 250,
    "staRequerido": 60,
    "minSkill": 75,
    "tipo": 1,
    "target": 4,
    "minHP": 15,
    "maxHP": 50,
    "wav": 27,
    "fx": 7
  },
  {
    "id": 16,
    "nombre": "Llamado musical",
    "desc": "Implora el espiritu musical, un bardo acudirá en tu ayuda.",
    "palabrasMagicas": "Impendere et worg",
    "manaRequerido": 460,
    "staRequerido": 35,
    "minSkill": 50,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 49,
    "fx": 0
  },
  {
    "id": 17,
    "nombre": "Llamado a la naturaleza",
    "desc": "Trae tres lobos que ayudarán a tu causa.",
    "palabrasMagicas": "Lüpus Aident",
    "manaRequerido": 250,
    "staRequerido": 40,
    "minSkill": 30,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 124,
    "fx": 0
  },
  {
    "id": 18,
    "nombre": "Celeridad",
    "desc": "Aumenta la agilidad del usuario que recibe el spell",
    "palabrasMagicas": "YUP A'INC",
    "manaRequerido": 60,
    "staRequerido": 20,
    "minSkill": 23,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 230,
    "fx": 0
  },
  {
    "id": 19,
    "nombre": "Torpeza",
    "desc": "Reduce la agilidad del usuario que recibe el spell",
    "palabrasMagicas": "ASYNC YUP A'INC",
    "manaRequerido": 40,
    "staRequerido": 10,
    "minSkill": 30,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 0
  },
  {
    "id": 20,
    "nombre": "Fuerza",
    "desc": "Aumenta la fuerza del objetivo",
    "palabrasMagicas": "Ar A'kron",
    "manaRequerido": 75,
    "staRequerido": 25,
    "minSkill": 35,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 230,
    "fx": 0
  },
  {
    "id": 21,
    "nombre": "Debilidad",
    "desc": "Reduce la fuerza del usuario que recibe el spell",
    "palabrasMagicas": "Xoom Varp",
    "manaRequerido": 50,
    "staRequerido": 15,
    "minSkill": 35,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 0
  },
  {
    "id": 22,
    "nombre": "Desencantar",
    "desc": "Desencantar remueve todo efecto mágico del usuario que lo conjure.",
    "palabrasMagicas": "Disincanto",
    "manaRequerido": 1250,
    "staRequerido": 180,
    "minSkill": 100,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 59,
    "fx": 30
  },
  {
    "id": 23,
    "nombre": "Corriente eléctrica",
    "desc": "Causa 20 a 70 puntos de daño en un área de cuatro tiles.",
    "palabrasMagicas": "T'HY KOOOL",
    "manaRequerido": 300,
    "staRequerido": 70,
    "minSkill": 75,
    "tipo": 1,
    "target": 4,
    "minHP": 20,
    "maxHP": 70,
    "wav": 56,
    "fx": 11
  },
  {
    "id": 24,
    "nombre": "Inmovilizar",
    "desc": "Impide que la víctima se movilize.",
    "palabrasMagicas": "Är Prop s'uo",
    "manaRequerido": 250,
    "staRequerido": 60,
    "minSkill": 55,
    "tipo": 2,
    "target": 3,
    "minHP": 0,
    "maxHP": 0,
    "wav": 253,
    "fx": 12
  },
  {
    "id": 25,
    "nombre": "Apocalipsis",
    "desc": "Causa 50 a 90 puntos de daño en un area de cuatro tiles.",
    "palabrasMagicas": "Rahma Nañarak O'al",
    "manaRequerido": 950,
    "staRequerido": 120,
    "minSkill": 80,
    "tipo": 1,
    "target": 4,
    "minHP": 50,
    "maxHP": 90,
    "wav": 65,
    "fx": 45
  },
  {
    "id": 26,
    "nombre": "Invocar elemental de fuego",
    "desc": "Invocar elemental de fuego",
    "palabrasMagicas": "Yur'rax",
    "manaRequerido": 740,
    "staRequerido": 100,
    "minSkill": 100,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 7
  },
  {
    "id": 27,
    "nombre": "Invocar elemental de agua",
    "desc": "Invocar elemental de ague",
    "palabrasMagicas": "Mantra'rax",
    "manaRequerido": 780,
    "staRequerido": 110,
    "minSkill": 90,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 7
  },
  {
    "id": 28,
    "nombre": "Invocar elemental de tierra",
    "desc": "Invocar elemental de tierra",
    "palabrasMagicas": "Mantra'rax",
    "manaRequerido": 800,
    "staRequerido": 100,
    "minSkill": 100,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 7
  },
  {
    "id": 29,
    "nombre": "Implorar ayuda",
    "desc": "Implorar ayuda",
    "palabrasMagicas": "Ar'Cos Mantra'rax",
    "manaRequerido": 2000,
    "staRequerido": 240,
    "minSkill": 100,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 7
  },
  {
    "id": 30,
    "nombre": "Te Violo",
    "desc": "Te Violo",
    "palabrasMagicas": "TE VIOLE!!!",
    "manaRequerido": 1,
    "staRequerido": 1000,
    "minSkill": 100,
    "tipo": 1,
    "target": 3,
    "minHP": 10000,
    "maxHP": 10000,
    "wav": 65,
    "fx": 18
  },
  {
    "id": 31,
    "nombre": "Curacion",
    "desc": "Curacion",
    "palabrasMagicas": "Me Cureh",
    "manaRequerido": 4000,
    "staRequerido": 1000,
    "minSkill": 50,
    "tipo": 1,
    "target": 1,
    "minHP": 1000,
    "maxHP": 1000,
    "wav": 17,
    "fx": 0
  },
  {
    "id": 32,
    "nombre": "Sanar",
    "desc": "Restaura entre 60 y 100 de daño al usuario y remueve todos los efectos negativos que éste pueda tener.",
    "palabrasMagicas": "Nihil Vitae",
    "manaRequerido": 750,
    "staRequerido": 150,
    "minSkill": 80,
    "tipo": 1,
    "target": 1,
    "minHP": 60,
    "maxHP": 100,
    "wav": 55,
    "fx": 36
  },
  {
    "id": 33,
    "nombre": "Desatar la ira",
    "desc": "Desatar la ira reduce la fuerza y la agilidad del usuario críticamente.",
    "palabrasMagicas": "Hic Dei",
    "manaRequerido": 1440,
    "staRequerido": 250,
    "minSkill": 90,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 32,
    "fx": 24
  },
  {
    "id": 34,
    "nombre": "Implosión",
    "desc": "Causa 120 a 150 puntos de daño a la victima.",
    "palabrasMagicas": "Nihil Mortem",
    "manaRequerido": 1400,
    "staRequerido": 120,
    "minSkill": 100,
    "tipo": 1,
    "target": 3,
    "minHP": 128,
    "maxHP": 136,
    "wav": 65,
    "fx": 18
  },
  {
    "id": 35,
    "nombre": "Lluvia de Mosquitos",
    "desc": "Los insectos paralizarán y dejaran ciega a la victima.",
    "palabrasMagicas": "Hut Inefectus",
    "manaRequerido": 2600,
    "staRequerido": 300,
    "minSkill": 100,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 26,
    "fx": 3
  },
  {
    "id": 36,
    "nombre": "Hechizo de NPC",
    "desc": "",
    "palabrasMagicas": "",
    "manaRequerido": 0,
    "staRequerido": 0,
    "minSkill": 0,
    "tipo": 1,
    "target": 3,
    "minHP": 30,
    "maxHP": 50,
    "wav": 27,
    "fx": 7
  },
  {
    "id": 37,
    "nombre": "HechizoNPCB",
    "desc": "Hechizo de NPC.",
    "palabrasMagicas": "",
    "manaRequerido": 0,
    "staRequerido": 0,
    "minSkill": 0,
    "tipo": 1,
    "target": 3,
    "minHP": 90,
    "maxHP": 120,
    "wav": 10,
    "fx": 14
  },
  {
    "id": 38,
    "nombre": "Metamorfosis: Gólem",
    "desc": "Transforma al usuario en un Gólem, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 1000,
    "staRequerido": 200,
    "minSkill": 100,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 39,
    "nombre": "Metamorfosis: Dragón",
    "desc": "Transforma al usuario en un Dragón, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 1300,
    "staRequerido": 250,
    "minSkill": 100,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 40,
    "nombre": "Metamorfosis: Lobo",
    "desc": "Transforma al usuario en un Lobo, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 100,
    "staRequerido": 20,
    "minSkill": 15,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 41,
    "nombre": "Metamorfosis: Ogro",
    "desc": "Transforma al usuario en un Ogro, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 600,
    "staRequerido": 40,
    "minSkill": 70,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 42,
    "nombre": "Metamorfosis: Jabalí",
    "desc": "Transforma al usuario en un Jabalí, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 100,
    "staRequerido": 30,
    "minSkill": 15,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 43,
    "nombre": "Metamorfosis: Árbol",
    "desc": "Transforma al usuario en un Árbol, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 900,
    "staRequerido": 100,
    "minSkill": 90,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 44,
    "nombre": "Metamorfosis: Oso Pardo",
    "desc": "Transforma al usuario en un Oso Pardo, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 200,
    "staRequerido": 40,
    "minSkill": 20,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 45,
    "nombre": "Metamorfosis: Tortuga",
    "desc": "Transforma al usuario en una Tortuga, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 200,
    "staRequerido": 40,
    "minSkill": 30,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 46,
    "nombre": "Metamorfosis: Araña",
    "desc": "Transforma al usuario en una Araña, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 300,
    "staRequerido": 60,
    "minSkill": 50,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 47,
    "nombre": "Metamorfosis: Demonio",
    "desc": "Transforma al usuario en un Demonio, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 600,
    "staRequerido": 70,
    "minSkill": 70,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 48,
    "nombre": "Metamorfosis: Serpiente",
    "desc": "Transforma al usuario en una Serpiente, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 50,
    "staRequerido": 10,
    "minSkill": 5,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 49,
    "nombre": "Metamorfosis: Murciélago",
    "desc": "Transforma al usuario en un Murciélago, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 50,
    "staRequerido": 10,
    "minSkill": 5,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 50,
    "nombre": "Metamorfosis: Tigre",
    "desc": "Transforma al usuario en un Tigre, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    "palabrasMagicas": "",
    "manaRequerido": 100,
    "staRequerido": 30,
    "minSkill": 15,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 57,
    "fx": 0
  },
  {
    "id": 51,
    "nombre": "HechizoNPCC",
    "desc": "Hechizo de NPC.",
    "palabrasMagicas": "",
    "manaRequerido": 0,
    "staRequerido": 0,
    "minSkill": 0,
    "tipo": 1,
    "target": 1,
    "minHP": 60,
    "maxHP": 100,
    "wav": 56,
    "fx": 11
  },
  {
    "id": 52,
    "nombre": "Juicio final",
    "desc": "Causa 150 a 180 puntos de daño a la victima.",
    "palabrasMagicas": "Finis Mortem",
    "manaRequerido": 1800,
    "staRequerido": 250,
    "minSkill": 100,
    "tipo": 1,
    "target": 3,
    "minHP": 142,
    "maxHP": 152,
    "wav": 66,
    "fx": 20
  },
  {
    "id": 53,
    "nombre": "Portal planar",
    "desc": "El hechizo Portal planar crea un teleport hacia tu hogar de orígen.",
    "palabrasMagicas": "Opercure Dimentia",
    "manaRequerido": 2300,
    "staRequerido": 300,
    "minSkill": 100,
    "tipo": 3,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 129,
    "fx": 39
  },
  {
    "id": 54,
    "nombre": "Resurrección",
    "desc": "Revive completamente a un usuario.",
    "palabrasMagicas": "HÎC KNÄ XÄR",
    "manaRequerido": 840,
    "staRequerido": 200,
    "minSkill": 100,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 100,
    "fx": 0
  },
  {
    "id": 55,
    "nombre": "Materializar: Comida",
    "desc": "Los hechizos de materialización convierten magia en materia. Este hechizo puede crear comida a partir de su lanzamiento.",
    "palabrasMagicas": "Sunt Alifens",
    "manaRequerido": 500,
    "staRequerido": 120,
    "minSkill": 90,
    "tipo": 7,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 130,
    "fx": 0
  },
  {
    "id": 56,
    "nombre": "Incinerar",
    "desc": "Una llamarada incinerará al objetivo, causando un daño considerable rápidamente.",
    "palabrasMagicas": "Incinera Corps",
    "manaRequerido": 920,
    "staRequerido": 100,
    "minSkill": 90,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 123,
    "fx": 16
  },
  {
    "id": 57,
    "nombre": "Tormenta ácida",
    "desc": "Causa 20 a 70 puntos de daño y envenena en un área de tres tiles.",
    "palabrasMagicas": "VAX IN XORP",
    "manaRequerido": 400,
    "staRequerido": 100,
    "minSkill": 80,
    "tipo": 1,
    "target": 4,
    "minHP": 20,
    "maxHP": 70,
    "wav": 127,
    "fx": 32
  },
  {
    "id": 58,
    "nombre": "Maldición",
    "desc": "Impide que la víctima ataque.",
    "palabrasMagicas": "Malefectus Sunt",
    "manaRequerido": 1800,
    "staRequerido": 10,
    "minSkill": 55,
    "tipo": 1,
    "target": 3,
    "minHP": 33,
    "maxHP": 45,
    "wav": 16,
    "fx": 24
  },
  {
    "id": 59,
    "nombre": "Llamado al familiar",
    "desc": "Llama o retira tu familiar",
    "palabrasMagicas": "Familiarê Asimis",
    "manaRequerido": 0,
    "staRequerido": 0,
    "minSkill": 0,
    "tipo": 6,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 130,
    "fx": 7
  },
  {
    "id": 60,
    "nombre": "Materializar: Bebida",
    "desc": "Los hechizos de materialización convierten magia en materia. Este hechizo puede crear bebida a partir de su lanzamiento.",
    "palabrasMagicas": "Sunt Aquum",
    "manaRequerido": 500,
    "staRequerido": 120,
    "minSkill": 90,
    "tipo": 7,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 130,
    "fx": 0
  },
  {
    "id": 61,
    "nombre": "Señal a tu mascota",
    "desc": "Llama o retira tu mascota",
    "palabrasMagicas": "",
    "manaRequerido": 0,
    "staRequerido": 0,
    "minSkill": 0,
    "tipo": 6,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 0,
    "fx": 0
  },
  {
    "id": 62,
    "nombre": "Detectar invisibilidad",
    "desc": "Detecta todo usuario invisible en el rango de visión del usuario.",
    "palabrasMagicas": "Fant Visiblî",
    "manaRequerido": 1800,
    "staRequerido": 300,
    "minSkill": 95,
    "tipo": 12,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 130,
    "fx": 0
  },
  {
    "id": 63,
    "nombre": "Lamento de la Banshee",
    "desc": "Causa 90 a 145 puntos de daño en un área de ocho tiles.",
    "palabrasMagicas": "VÂR NI MÈS",
    "manaRequerido": 3020,
    "staRequerido": 300,
    "minSkill": 100,
    "tipo": 1,
    "target": 4,
    "minHP": 90,
    "maxHP": 145,
    "wav": 94,
    "fx": 45
  },
  {
    "id": 64,
    "nombre": "Veneno crítico",
    "desc": "Envenenamiento crítico, provoca la muerte rápidamente si no se contraresta con un antídoto.",
    "palabrasMagicas": "Nihil Xôn In",
    "manaRequerido": 250,
    "staRequerido": 90,
    "minSkill": 60,
    "tipo": 2,
    "target": 3,
    "minHP": 0,
    "maxHP": 0,
    "wav": 127,
    "fx": 3
  },
  {
    "id": 65,
    "nombre": "Tornado",
    "desc": "Paraliza en un área de dos tiles.",
    "palabrasMagicas": "Ênt Naturâ Veé",
    "manaRequerido": 1400,
    "staRequerido": 300,
    "minSkill": 100,
    "tipo": 2,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 129,
    "fx": 44
  },
  {
    "id": 66,
    "nombre": "Terror 'Rey Dragón",
    "desc": "Hechizo de NPC.",
    "palabrasMagicas": "",
    "manaRequerido": 1440,
    "staRequerido": 100,
    "minSkill": 90,
    "tipo": 8,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 32,
    "fx": 24
  },
  {
    "id": 67,
    "nombre": "Curar heridas críticas",
    "desc": "Curar heridas críticas, restaura entre 30 y 60 puntos de salud.",
    "palabrasMagicas": "CORP CURATIO",
    "manaRequerido": 120,
    "staRequerido": 80,
    "minSkill": 65,
    "tipo": 1,
    "target": 3,
    "minHP": 30,
    "maxHP": 60,
    "wav": 240,
    "fx": 9
  },
  {
    "id": 68,
    "nombre": "Palabra sagrada",
    "desc": "Hechizo deshabilitado temporalmente",
    "palabrasMagicas": "SACRE ASTAIM",
    "manaRequerido": 900,
    "staRequerido": 80,
    "minSkill": 62,
    "tipo": 0,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 0,
    "fx": 0
  },
  {
    "id": 69,
    "nombre": "Descarga flamígera",
    "desc": "Castiga al enemigo con el fuego divino, causando entre 80 y 120 puntos de daño e incinerándolo",
    "palabrasMagicas": "Jâf Rashida",
    "manaRequerido": 1150,
    "staRequerido": 75,
    "minSkill": 90,
    "tipo": 2,
    "target": 1,
    "minHP": 80,
    "maxHP": 120,
    "wav": 27,
    "fx": 48
  },
  {
    "id": 70,
    "nombre": "Aura sagrada",
    "desc": "Hechizo deshabilitado temporalmente",
    "palabrasMagicas": "Ajàunis Herinoenous",
    "manaRequerido": 720,
    "staRequerido": 150,
    "minSkill": 50,
    "tipo": 10,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 0,
    "fx": 0
  },
  {
    "id": 71,
    "nombre": "Pregonar la palabra de Dios",
    "desc": "Cura en un diámetro de 5 tiles entre 75 y 125 puntos de vida",
    "palabrasMagicas": "In nómini Pater, Filum, Sanctis Espiritum",
    "manaRequerido": 1000,
    "staRequerido": 350,
    "minSkill": 70,
    "tipo": 1,
    "target": 4,
    "minHP": 75,
    "maxHP": 125,
    "wav": 103,
    "fx": 0
  },
  {
    "id": 72,
    "nombre": "Golpe certero",
    "desc": "El receptor no fallará el próximo golpe",
    "palabrasMagicas": "Ar'Sen Benerim",
    "manaRequerido": 1480,
    "staRequerido": 300,
    "minSkill": 90,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 55,
    "fx": 0
  },
  {
    "id": 73,
    "nombre": "Poder divino",
    "desc": "El poder del receptor aumenta considerablemente",
    "palabrasMagicas": "Ar'Sen Benerim",
    "manaRequerido": 1160,
    "staRequerido": 200,
    "minSkill": 90,
    "tipo": 8,
    "target": 1,
    "minHP": 55,
    "maxHP": 70,
    "wav": 0,
    "fx": 0
  },
  {
    "id": 74,
    "nombre": "Animar a la naturaleza",
    "desc": "Le da vida momentáneamente a un árbol.",
    "palabrasMagicas": "In amari söpra T'ai",
    "manaRequerido": 1000,
    "staRequerido": 0,
    "minSkill": 70,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 57
  },
  {
    "id": 75,
    "nombre": "Círculo curativo",
    "desc": "Curar entre 25 y 35 puntos de salud en un diámetro de 3 tiles.",
    "palabrasMagicas": "AMAÎRI SANCTIS",
    "manaRequerido": 300,
    "staRequerido": 90,
    "minSkill": 45,
    "tipo": 1,
    "target": 4,
    "minHP": 25,
    "maxHP": 35,
    "wav": 18,
    "fx": 0
  },
  {
    "id": 76,
    "nombre": "Semillas de fuego",
    "desc": "Bellotas y bayas se convierten en bolas de fuego, causando 85 a 120 puntos de daño.",
    "palabrasMagicas": "Samarin Tar",
    "manaRequerido": 1250,
    "staRequerido": 100,
    "minSkill": 85,
    "tipo": 1,
    "target": 3,
    "minHP": 100,
    "maxHP": 130,
    "wav": 204,
    "fx": 43
  },
  {
    "id": 77,
    "nombre": "Rayo solar",
    "desc": "Haz de luz que ciega e inflige 50 a 100 puntos de daño.",
    "palabrasMagicas": "Pelor In bodem",
    "manaRequerido": 1350,
    "staRequerido": 125,
    "minSkill": 100,
    "tipo": 1,
    "target": 3,
    "minHP": 50,
    "maxHP": 100,
    "wav": 27,
    "fx": 34
  },
  {
    "id": 78,
    "nombre": "Terremoto",
    "desc": "Causa entre 50 y 75 puntos de daño en un radio de 3 tiles.",
    "palabrasMagicas": "Nature Obad-Hai Eventî",
    "manaRequerido": 1180,
    "staRequerido": 200,
    "minSkill": 95,
    "tipo": 1,
    "target": 4,
    "minHP": 50,
    "maxHP": 75,
    "wav": 65,
    "fx": 0
  },
  {
    "id": 79,
    "nombre": "Resucitar familiar o mascota",
    "desc": "Resucita el familiar o mascota del objetivo.",
    "palabrasMagicas": "Nature Xâr",
    "manaRequerido": 600,
    "staRequerido": 120,
    "minSkill": 70,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 55,
    "fx": 0
  },
  {
    "id": 80,
    "nombre": "Sirviente invisible",
    "desc": "Hechizo De Bardo",
    "palabrasMagicas": "Sama gerëi",
    "manaRequerido": 250,
    "staRequerido": 250,
    "minSkill": 82,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 7
  },
  {
    "id": 81,
    "nombre": "Mirada penetrante",
    "desc": "Hechizo de Bardo",
    "palabrasMagicas": "Teliönem Enneryl",
    "manaRequerido": 200,
    "staRequerido": 120,
    "minSkill": 45,
    "tipo": 2,
    "target": 3,
    "minHP": 0,
    "maxHP": 0,
    "wav": 16,
    "fx": 8
  },
  {
    "id": 82,
    "nombre": "Intimidar al espíritu",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "Mortem",
    "manaRequerido": 75,
    "staRequerido": 200,
    "minSkill": 80,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 0
  },
  {
    "id": 83,
    "nombre": "Cobijo seguro de Leomundo",
    "desc": "Hechizo De Bardo",
    "palabrasMagicas": "Leomund secure cobijim",
    "manaRequerido": 360,
    "staRequerido": 40,
    "minSkill": 55,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 92,
    "fx": 0
  },
  {
    "id": 84,
    "nombre": "Lamento de las almas",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "Espirictum Nifis Mortem",
    "manaRequerido": 1620,
    "staRequerido": 300,
    "minSkill": 100,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 105,
    "fx": 45
  },
  {
    "id": 85,
    "nombre": "Inspiracion",
    "desc": "Hechizo de bardo",
    "palabrasMagicas": "Inspiratum",
    "manaRequerido": 720,
    "staRequerido": 250,
    "minSkill": 85,
    "tipo": 1,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 30,
    "fx": 24
  },
  {
    "id": 86,
    "nombre": "Asistencia divina",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "In Enterinum Zôrx",
    "manaRequerido": 9999,
    "staRequerido": 250,
    "minSkill": 75,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 17,
    "fx": 7
  },
  {
    "id": 87,
    "nombre": "Castigo Divino",
    "desc": "Causa 75 a 100 puntos de daño a la victima.",
    "palabrasMagicas": "Abra Ainum",
    "manaRequerido": 570,
    "staRequerido": 300,
    "minSkill": 80,
    "tipo": 1,
    "target": 1,
    "minHP": 75,
    "maxHP": 100,
    "wav": 27,
    "fx": 11
  },
  {
    "id": 88,
    "nombre": "Fuente de vida",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "Abra Ainum",
    "manaRequerido": 9999,
    "staRequerido": 150,
    "minSkill": 60,
    "tipo": 1,
    "target": 3,
    "minHP": 75,
    "maxHP": 100,
    "wav": 55,
    "fx": 11
  },
  {
    "id": 89,
    "nombre": "Honor del Paladín",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "Ar'Cos Sanctis Hic",
    "manaRequerido": 500,
    "staRequerido": 300,
    "minSkill": 100,
    "tipo": 1,
    "target": 1,
    "minHP": 100,
    "maxHP": 140,
    "wav": 103,
    "fx": 0
  },
  {
    "id": 90,
    "nombre": "Prevención del mal",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "Rohl A'Inc",
    "manaRequerido": 9999,
    "staRequerido": 200,
    "minSkill": 50,
    "tipo": 2,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 0,
    "fx": 0
  },
  {
    "id": 91,
    "nombre": "Arma mágica",
    "desc": "Hechizo deshabilitado temporalmente.",
    "palabrasMagicas": "Sarapiens Herinoenous",
    "manaRequerido": 9999,
    "staRequerido": 200,
    "minSkill": 87,
    "tipo": 10,
    "target": 1,
    "minHP": 0,
    "maxHP": 0,
    "wav": 0,
    "fx": 0
  },
  {
    "id": 92,
    "nombre": "Misil mágico",
    "desc": "Causa 25 a 35 puntos de daño a la victima.",
    "palabrasMagicas": "INX TO RÂ",
    "manaRequerido": 40,
    "staRequerido": 20,
    "minSkill": 30,
    "tipo": 1,
    "target": 3,
    "minHP": 25,
    "maxHP": 35,
    "wav": 27,
    "fx": 10
  },
  {
    "id": 93,
    "nombre": "Descarga Eléctrica",
    "desc": "Causa 35 a 60 puntos de daño a la victima.",
    "palabrasMagicas": "T'HY KOOOL",
    "manaRequerido": 250,
    "staRequerido": 60,
    "minSkill": 65,
    "tipo": 1,
    "target": 3,
    "minHP": 35,
    "maxHP": 60,
    "wav": 234,
    "fx": 49
  },
  {
    "id": 94,
    "nombre": "Ráfaga ígnea",
    "desc": "Causa 55 a 70 puntos de daño a la victima.",
    "palabrasMagicas": "IGNÎS XAR",
    "manaRequerido": 720,
    "staRequerido": 95,
    "minSkill": 75,
    "tipo": 1,
    "target": 3,
    "minHP": 55,
    "maxHP": 70,
    "wav": 242,
    "fx": 11
  },
  {
    "id": 95,
    "nombre": "Invocar esqueletos",
    "desc": "Traerá tres esqueletos de los escombros.",
    "palabrasMagicas": "MoÎ côrps",
    "manaRequerido": 150,
    "staRequerido": 20,
    "minSkill": 20,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 105,
    "fx": 0
  },
  {
    "id": 96,
    "nombre": "Invocar zombies",
    "desc": "Invoca la ayuda del los muertos, tres zombies acudirán en tu ayuda.",
    "palabrasMagicas": "MoÎ cámus",
    "manaRequerido": 250,
    "staRequerido": 40,
    "minSkill": 30,
    "tipo": 4,
    "target": 4,
    "minHP": 0,
    "maxHP": 0,
    "wav": 105,
    "fx": 0
  },
  {
    "id": 97,
    "nombre": "Bomba mágica",
    "desc": "Causa 10 a 30 puntos de daño en un área de dos tiles.",
    "palabrasMagicas": "Drac né Xar",
    "manaRequerido": 50,
    "staRequerido": 20,
    "minSkill": 38,
    "tipo": 1,
    "target": 4,
    "minHP": 10,
    "maxHP": 30,
    "wav": 138,
    "fx": 49
  },
  {
    "id": 98,
    "nombre": "Hechizo de la vaca loca",
    "desc": "",
    "palabrasMagicas": "",
    "manaRequerido": 0,
    "staRequerido": 0,
    "minSkill": 0,
    "tipo": 1,
    "target": 3,
    "minHP": 80,
    "maxHP": 110,
    "wav": 8,
    "fx": 7
  },
  {
    "id": 99,
    "nombre": "Mata Elementales/Bardos",
    "desc": "Causa 150 a 180 puntos de daño a la victima.",
    "palabrasMagicas": "Mohil Mortem",
    "manaRequerido": 5000,
    "staRequerido": 0,
    "minSkill": 100,
    "tipo": 1,
    "target": 2,
    "minHP": 300,
    "maxHP": 400,
    "wav": 66,
    "fx": 20
  },
  {
    "id": 100,
    "nombre": "Curar heridas graves GMs",
    "desc": "Curar heridas graves, restaura La vida entera.",
    "palabrasMagicas": "Toma toda la Vida.",
    "manaRequerido": 0,
    "staRequerido": 5,
    "minSkill": 0,
    "tipo": 1,
    "target": 3,
    "minHP": 5000,
    "maxHP": 5000,
    "wav": 18,
    "fx": 9
  },
  {
    "id": 101,
    "nombre": "Apocalipsis GMs",
    "desc": "Causa 50 a 90 puntos de daño en un area de cuatro tiles.",
    "palabrasMagicas": "Rahma Nañarak O'al '^GM^'",
    "manaRequerido": 1,
    "staRequerido": 1,
    "minSkill": 80,
    "tipo": 1,
    "target": 4,
    "minHP": 500,
    "maxHP": 900,
    "wav": 65,
    "fx": 115
  }
];
