import type { CharacterClassId } from "./catalog";
import type { ItemSpecialUse } from "./itemSpecialUse";

const ALL_CLASSES: CharacterClassId[] = [
  "paladin",
  "clerigo",
  "mago",
  "nigromante",
  "druida",
  "bardo",
  "guerrero",
  "cazador",
  "asesino",
];

const DRUID_ONLY: CharacterClassId[] = ["druida"];

const OTHER_ITEMS_BASE = "/assets/ao/otherItems";

export type OtherMiscItemEntry = {
  itemId: string;
  idItem: number;
  nivelMinimo: number;
  nombre: string;
  valor: number;
  usableBy: CharacterClassId[];
  iconAssetPath: string;
  maxStack?: number;
  noDropeaAlMorir?: boolean;
  /** Doble click en inventario dispara el uso especial. */
  usableFromInventory?: boolean;
  specialUse?: ItemSpecialUse;
};

function misc(
  entry: Omit<OtherMiscItemEntry, "usableBy" | "nivelMinimo" | "valor"> &
    Partial<Pick<OtherMiscItemEntry, "usableBy" | "nivelMinimo" | "valor">>
): OtherMiscItemEntry {
  return {
    nivelMinimo: 1,
    valor: 100,
    usableBy: ALL_CLASSES,
    ...entry,
  };
}

/** Objetos en `public/assets/ao/otherItems` (excepto consumibles ya en CONSUMABLES). */
export const OTHER_MISC_ITEMS: OtherMiscItemEntry[] = [
  misc({
    itemId: "anillo_artes_marciales",
    idItem: 4101,
    nombre: "Anillo de Artes Marciales",
    iconAssetPath: `${OTHER_ITEMS_BASE}/anilloArtesMarciales.png`,
    valor: 12000,
    specialUse: { kind: "future", note: "Bonificaciones de artes marciales (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "anillo_espectral_ii",
    idItem: 4102,
    nombre: "Anillo Espectral II",
    iconAssetPath: `${OTHER_ITEMS_BASE}/anilloEspectral2.png`,
    valor: 18000,
    nivelMinimo: 25,
    specialUse: { kind: "future", note: "Variante del anillo espectral (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "anillo_ocultacion",
    idItem: 4103,
    nombre: "Anillo de Ocultación",
    iconAssetPath: `${OTHER_ITEMS_BASE}/anilloOcultacion.png`,
    valor: 14000,
    specialUse: { kind: "future", note: "Ocultación pasiva (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "anillo_ogro",
    idItem: 4104,
    nombre: "Anillo del Ogro",
    iconAssetPath: `${OTHER_ITEMS_BASE}/anilloOgro.png`,
    valor: 9500,
    specialUse: { kind: "future", note: "Fuerza del ogro (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "anillo_sombras",
    idItem: 4105,
    nombre: "Anillo de Sombras",
    iconAssetPath: `${OTHER_ITEMS_BASE}/anilloSombras.png`,
    valor: 16000,
    specialUse: { kind: "future", note: "Sigilo y sombras (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "barca",
    idItem: 4106,
    nombre: "Barca",
    iconAssetPath: `${OTHER_ITEMS_BASE}/barca.png`,
    valor: 2500,
    noDropeaAlMorir: true,
    specialUse: { kind: "boat_navigation" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "montura_caballo_mago",
    idItem: 4107,
    nombre: "Caballo (mago)",
    iconAssetPath: `${OTHER_ITEMS_BASE}/caballoMago.png`,
    valor: 8000,
    specialUse: { kind: "mount", mountId: "caballo_mago" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "montura_caballo_negro",
    idItem: 4108,
    nombre: "Caballo negro",
    iconAssetPath: `${OTHER_ITEMS_BASE}/caballoNigro.png`,
    valor: 12000,
    specialUse: { kind: "mount", mountId: "caballo_negro" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "montura_caballo_nw",
    idItem: 4109,
    nombre: "Caballo del Noroeste",
    iconAssetPath: `${OTHER_ITEMS_BASE}/caballoNw.png`,
    valor: 10000,
    specialUse: { kind: "mount", mountId: "caballo_nw" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "montura_caballo_semielfo",
    idItem: 4110,
    nombre: "Caballo semielfo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/caballoSemi.png`,
    valor: 9000,
    specialUse: { kind: "mount", mountId: "caballo_semielfo" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "montura_huargo",
    idItem: 4111,
    nombre: "Huargo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/montuHuargo.png`,
    valor: 15000,
    specialUse: { kind: "mount", mountId: "huargo" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "hipocampo",
    idItem: 4112,
    nombre: "Hipocampo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/hipocampo.png`,
    valor: 18000,
    specialUse: { kind: "boat_navigation" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "corteza_ent",
    idItem: 4113,
    nombre: "Corteza de Ent",
    iconAssetPath: `${OTHER_ITEMS_BASE}/cortezaEnt.png`,
    valor: 3200,
    usableBy: DRUID_ONLY,
    nivelMinimo: 12,
    specialUse: { kind: "druid_polymorph", mobFormId: "ent" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "diente_lobo",
    idItem: 4114,
    nombre: "Diente de Lobo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/dienteLobo.png`,
    valor: 800,
    usableBy: DRUID_ONLY,
    specialUse: { kind: "druid_polymorph", mobFormId: "lobo" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "escama_dragon",
    idItem: 4115,
    nombre: "Escama de Dragón",
    iconAssetPath: `${OTHER_ITEMS_BASE}/escamaDragon.png`,
    valor: 25000,
    usableBy: DRUID_ONLY,
    nivelMinimo: 30,
    specialUse: { kind: "druid_polymorph", mobFormId: "dragon" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "garra_tigre",
    idItem: 4116,
    nombre: "Garra de Tigre",
    iconAssetPath: `${OTHER_ITEMS_BASE}/garraTigre.png`,
    valor: 4500,
    usableBy: DRUID_ONLY,
    nivelMinimo: 18,
    specialUse: { kind: "druid_polymorph", mobFormId: "tigre" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "gema_azul",
    idItem: 4117,
    nombre: "Gema Azul",
    iconAssetPath: `${OTHER_ITEMS_BASE}/gemaAzul.png`,
    valor: 5000,
    maxStack: 100,
    specialUse: { kind: "future", note: "Uso en comercio o crafteo (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "gema_dorada",
    idItem: 4118,
    nombre: "Gema Dorada",
    iconAssetPath: `${OTHER_ITEMS_BASE}/gemaDorada.png`,
    valor: 50000,
    maxStack: 10,
    specialUse: { kind: "clan_founding_gem", gemTier: "dorada" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "gema_gris",
    idItem: 4119,
    nombre: "Gema Gris",
    iconAssetPath: `${OTHER_ITEMS_BASE}/gemaGris.png`,
    valor: 35000,
    maxStack: 10,
    specialUse: { kind: "clan_founding_gem", gemTier: "gris" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "gema_lunar",
    idItem: 4120,
    nombre: "Gema Lunar",
    iconAssetPath: `${OTHER_ITEMS_BASE}/gemaLunar.png`,
    valor: 45000,
    maxStack: 10,
    specialUse: { kind: "clan_founding_gem", gemTier: "lunar" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "gema_naranja",
    idItem: 4121,
    nombre: "Gema Naranja",
    iconAssetPath: `${OTHER_ITEMS_BASE}/gemaNaranja.png`,
    valor: 40000,
    maxStack: 10,
    specialUse: { kind: "clan_founding_gem", gemTier: "naranja" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "mineral_hierro",
    idItem: 4122,
    nombre: "Mineral de Hierro",
    iconAssetPath: `${OTHER_ITEMS_BASE}/mineralHierro.png`,
    valor: 120,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Herrería y crafteo (pendiente)." },
  }),
  misc({
    itemId: "mineral_oro",
    idItem: 4123,
    nombre: "Mineral de Oro",
    iconAssetPath: `${OTHER_ITEMS_BASE}/mineralOro.png`,
    valor: 800,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Herrería y crafteo (pendiente)." },
  }),
  misc({
    itemId: "mineral_plata",
    idItem: 4124,
    nombre: "Mineral de Plata",
    iconAssetPath: `${OTHER_ITEMS_BASE}/mineralPlata.png`,
    valor: 350,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Herrería y crafteo (pendiente)." },
  }),
  misc({
    itemId: "orbe_ponzona",
    idItem: 4125,
    nombre: "Orbe de Ponzoña",
    iconAssetPath: `${OTHER_ITEMS_BASE}/orbePonzoña.png`,
    valor: 22000,
    specialUse: { kind: "future", note: "Venenos y alquimia (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pargo",
    idItem: 4126,
    nombre: "Pargo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pargo.png`,
    valor: 45,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Cocina y trueque (pendiente)." },
  }),
  misc({
    itemId: "pelaje_oso",
    idItem: 4127,
    nombre: "Pelaje de Oso",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pelajeOso.png`,
    valor: 2200,
    usableBy: DRUID_ONLY,
    nivelMinimo: 10,
    specialUse: { kind: "druid_polymorph", mobFormId: "oso" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pendiente_experto",
    idItem: 4128,
    nombre: "Pendiente del Experto",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pendienteExperto.png`,
    valor: 11000,
    specialUse: { kind: "future", note: "Bonos de experiencia (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pendiente_sacrificial",
    idItem: 4129,
    nombre: "Pendiente Sacrificial",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pendienteSacri.png`,
    valor: 8500,
    specialUse: { kind: "future", note: "Rituales y sacrificios (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pez_espada",
    idItem: 4130,
    nombre: "Pez Espada",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pezEspada_icon.png`,
    valor: 180,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Cocina y misiones (pendiente)." },
  }),
  misc({
    itemId: "piedra_golem",
    idItem: 4131,
    nombre: "Piedra de Gólem",
    iconAssetPath: `${OTHER_ITEMS_BASE}/piedraGolem.png`,
    valor: 6000,
    usableBy: DRUID_ONLY,
    nivelMinimo: 22,
    specialUse: { kind: "druid_polymorph", mobFormId: "golem" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "piel_lobo",
    idItem: 4132,
    nombre: "Piel de Lobo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pielLobo.png`,
    valor: 650,
    usableBy: DRUID_ONLY,
    specialUse: { kind: "druid_polymorph", mobFormId: "lobo" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "piel_lobo_invernal",
    idItem: 4133,
    nombre: "Piel de Lobo Invernal",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pielLoboInver.png`,
    valor: 2800,
    usableBy: DRUID_ONLY,
    nivelMinimo: 15,
    specialUse: { kind: "druid_polymorph", mobFormId: "lobo_invernal" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pluma",
    idItem: 4134,
    nombre: "Pluma",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pluma.png`,
    valor: 400,
    usableBy: DRUID_ONLY,
    specialUse: { kind: "druid_polymorph", mobFormId: "ave" },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pollo",
    idItem: 4135,
    nombre: "Pollo",
    iconAssetPath: `${OTHER_ITEMS_BASE}/pollo.png`,
    valor: 25,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Cocina (pendiente)." },
  }),
  misc({
    itemId: "red_pesca",
    idItem: 4136,
    nombre: "Red de Pesca",
    iconAssetPath: `${OTHER_ITEMS_BASE}/redPesca.png`,
    valor: 1500,
    specialUse: { kind: "future", note: "Pesca (pendiente)." },
    usableFromInventory: true,
  }),
  misc({
    itemId: "pergamino",
    idItem: 4137,
    nombre: "Pergamino",
    iconAssetPath: `${OTHER_ITEMS_BASE}/scroll.png`,
    valor: 500,
    maxStack: 10_000,
    specialUse: { kind: "future", note: "Inscripción de hechizos (pendiente)." },
    usableFromInventory: true,
  }),
];

export type OtherMiscItemId = (typeof OTHER_MISC_ITEMS)[number]["itemId"];
