import type { CharacterClassId } from "./items";

export const SPELL_ID = {
  CURAR_VENENO: 1,
  PROYECTIL_MAGICO: 2,
  CURAR_HERIDAS_LEVES: 3,
  SAETA_IGNEA: 4,
  PROYECTIL_ELECTRICO: 5,
  METAMORFOSIS_AGUILA: 6,
  IMPLOSION: 7,
  INMOVILIZAR: 8,
  CURAR_HERIDAS_GRAVES: 9,
  PARALIZAR: 10,
  TORMENTA_ELECTRICA: 11,
  REMOVER_PARALISIS: 102,
  RESUCITAR: 103,
} as const;

/** Hechizos que requieren llevar un Anillo Espectral en el inventario. */
export const SPELL_IDS_REQUIRING_ANILLO_ESPECTRAL = new Set<number>([
  SPELL_ID.IMPLOSION,
  25,  // Apocalipsis
  52,  // Juicio final
  63,  // Lamento de la Banshee
  69,  // Descarga flamígera
  76,  // Semillas de fuego
]);

export const IMMOBILIZE_SPELL_IDS = new Set<number>([
  SPELL_ID.INMOVILIZAR,
  SPELL_ID.PARALIZAR,
  35,
]);

export function spellRequiresAnilloEspectral(spellId: number): boolean {
  return SPELL_IDS_REQUIRING_ANILLO_ESPECTRAL.has(spellId);
}

export type SpellDefinition = {
  idSpell: number;
  nombre: string;
  descripcion: string;
  valor: number;
  nivelRequerido: number;
  manaCost: number;
  danioMin: number;
  danioMax: number;
  healMin: number;
  healMax: number;
  puedeUsarseEnAliados: boolean;
  remueveDebuff: string | null;
  usableBy: CharacterClassId[];
  iconAssetPath?: string;
  isStarter: boolean;
  /** true si afecta tiles alrededor del objetivo, no solo un tile. */
  aoe: boolean;
  /** Radio en tiles (Manhattan o redonda según implementación de combate). 0 si aoe es false. */
  aoeRadiusTiles: number;
};

export const SPELL_DEFINITIONS: SpellDefinition[] = [
  {
    idSpell: 1,
    nombre: "Curar Veneno",
    descripcion: "Purga toxinas y limpia el estado alterado del objetivo.",
    valor: 200,
    nivelRequerido: 0,
    manaCost: 15,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: "Envenenado",
    usableBy: ["paladin", "clerigo", "mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell1.png",
    isStarter: true,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 2,
    nombre: "Proyectil Magico",
    descripcion: "Concentra energia arcana en un disparo directo y veloz.",
    valor: 200,
    nivelRequerido: 0,
    manaCost: 20,
    danioMin: 10,
    danioMax: 16,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["paladin", "clerigo", "mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell2.png",
    isStarter: true,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 3,
    nombre: "Curar Heridas Leves",
    descripcion: "Cierra cortes y golpes menores con una plegaria curativa.",
    valor: 1000,
    nivelRequerido: 0,
    manaCost: 20,
    danioMin: 0,
    danioMax: 0,
    healMin: 15,
    healMax: 25,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["paladin", "clerigo", "mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell3.png",
    isStarter: true,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 4,
    nombre: "Saeta Ignea",
    descripcion: "Lanza una saeta de fuego.",
    valor: 1200,
    nivelRequerido: 0,
    manaCost: 18,
    danioMin: 18,
    danioMax: 30,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo"],
    iconAssetPath: "/assets/ao/spells/spell4.png",
    isStarter: true,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 5,
    nombre: "Proyectil Electrico",
    descripcion: "Invoca una descarga electrica dirigida.",
    valor: 2500,
    nivelRequerido: 12,
    manaCost: 30,
    danioMin: 30,
    danioMax: 46,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo"],
    iconAssetPath: "/assets/ao/spells/spell4.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 6,
    nombre: "Metamorfosis Aguila",
    descripcion: "Transforma temporalmente el objetivo.",
    valor: 2400,
    nivelRequerido: 0,
    manaCost: 25,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell2.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 7,
    nombre: "Implosion",
    descripcion: "Comprime energia oscura en un punto y la detona con violencia.",
    valor: 450000,
    nivelRequerido: 42,
    manaCost: 1500,
    danioMin: 160,
    danioMax: 188,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 8,
    nombre: "Inmovilizar",
    descripcion:
      "Invoca raices arcanas que enredan al objetivo y lo dejan sin poder moverse unos segundos.",
    valor: 28000,
    nivelRequerido: 24,
    manaCost: 280,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["paladin", "clerigo", "mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell5.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 9,
    nombre: "Curar Heridas Graves",
    descripcion:
      "Canaliza energia vital intensa para cerrar heridas profundas y restaurar gran cantidad de vida.",
    valor: 16000,
    nivelRequerido: 20,
    manaCost: 190,
    danioMin: 0,
    danioMax: 0,
    healMin: 45,
    healMax: 65,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["paladin", "clerigo", "mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell3.png",
    isStarter: true,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: SPELL_ID.PARALIZAR,
    nombre: "Paralizar",
    descripcion:
      "Descarga arcana que paraliza al objetivo, impidiéndole moverse durante un tiempo.",
    valor: 30000,
    nivelRequerido: 28,
    manaCost: 420,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["paladin", "clerigo", "mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell7.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: SPELL_ID.TORMENTA_ELECTRICA,
    nombre: "Tormenta Electrica",
    descripcion: "Invoca una tormenta eléctrica devastadora sobre el objetivo.",
    valor: 20000,
    nivelRequerido: 20,
    manaCost: 45,
    danioMin: 55,
    danioMax: 65,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell8.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 102,
    nombre: "Remover paralisis",
    descripcion: "Remueve la paralisis.",
    valor: 25000,
    nivelRequerido: 20,
    manaCost: 300,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: "Inmovilizado",
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell8.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 103,
    nombre: "Resucitar",
    descripcion: "Resucitar un usuario muerto.",
    valor: 75000,
    nivelRequerido: 32,
    manaCost: 800,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 13,
    nombre: "Furia de Uhkrul",
    descripcion: "Furia de Uhkrul, aumenta la fuerza y la agilidad del objetivo criticamente.",
    valor: 72000,
    nivelRequerido: 32,
    manaCost: 720,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/furia.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 14,
    nombre: "Invisibilidad",
    descripcion: "Vuelve invisible al objetivo, efecto no permanente.",
    valor: 120000,
    nivelRequerido: 36,
    manaCost: 600,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/invi.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 15,
    nombre: "Tormenta de fuego",
    descripcion: "Causa 15 a 50 puntos de daño en un área de tres tiles.",
    valor: 50000,
    nivelRequerido: 30,
    manaCost: 250,
    danioMin: 55,
    danioMax: 70,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell4.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 16,
    nombre: "Llamado musical",
    descripcion: "Implora el espiritu musical, un bardo acudirá en tu ayuda.",
    valor: 0,
    nivelRequerido: 30,
    manaCost: 460,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["bardo"],
    iconAssetPath: "/assets/ao/spells/spell6.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 17,
    nombre: "Llamado a la naturaleza",
    descripcion: "Trae tres lobos que ayudarán a tu causa.",
    valor: 18000,
    nivelRequerido: 30,
    manaCost: 250,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 18,
    nombre: "Celeridad",
    descripcion: "Aumenta la agilidad del usuario que recibe el spell",
    valor: 15000,
    nivelRequerido: 20,
    manaCost: 60,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell4.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 19,
    nombre: "Torpeza",
    descripcion: "Reduce la agilidad del usuario que recibe el spell",
    valor: 28000,
    nivelRequerido: 30,
    manaCost: 40,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell8.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 20,
    nombre: "Fuerza",
    descripcion: "Aumenta la fuerza del objetivo",
    valor: 18000,
    nivelRequerido: 20,
    manaCost: 75,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell3.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 21,
    nombre: "Debilidad",
    descripcion: "Reduce la fuerza del usuario que recibe el spell",
    valor: 30000,
    nivelRequerido: 35,
    manaCost: 50,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spellNegro.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 22,
    nombre: "Desencantar",
    descripcion: "Desencantar remueve todo efecto mágico del usuario que lo conjure.",
    valor: 50000,
    nivelRequerido: 36,
    manaCost: 820,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spellDruida.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 23,
    nombre: "Corriente eléctrica",
    descripcion: "Causa 20 a 70 puntos de daño en un área de cuatro tiles.",
    valor: 36000,
    nivelRequerido: 28,
    manaCost: 300,
    danioMin: 40,
    danioMax: 70,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell8.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 25,
    nombre: "Apocalipsis",
    descripcion: "Causa 50 a 90 puntos de daño en un area de cuatro tiles.",
    valor: 480000,
    nivelRequerido: 38,
    manaCost: 1050,
    danioMin: 145,
    danioMax: 155,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante"],
    iconAssetPath: "/assets/ao/spells/spellNegro.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 29,
    nombre: "Implorar ayuda",
    descripcion: "Implorar ayuda",
    valor: 0,
    nivelRequerido: 100,
    manaCost: 2000,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["clerigo"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 32,
    nombre: "Sanar",
    descripcion: "Restaura entre 60 y 100 de daño al usuario y remueve todos los efectos negativos que éste pueda tener.",
    valor: 88000,
    nivelRequerido: 38,
    manaCost: 880,
    danioMin: 0,
    danioMax: 0,
    healMin: 100,
    healMax: 110,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["clerigo"],
    iconAssetPath: "/assets/ao/spells/spell7.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 35,
    nombre: "Lluvia de Mosquitos",
    descripcion: "Los insectos paralizarán y dejaran ciega a la victima.",
    valor: 650000,
    nivelRequerido: 40,
    manaCost: 2200,
    danioMin: 80,
    danioMax: 90,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante"],
    iconAssetPath: "/assets/ao/spells/spellNegro.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 36,
    nombre: "Hechizo de NPC",
    descripcion: "",
    valor: 0,
    nivelRequerido: 0,
    manaCost: 0,
    danioMin: 30,
    danioMax: 50,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 37,
    nombre: "HechizoNPCB",
    descripcion: "Hechizo de NPC.",
    valor: 0,
    nivelRequerido: 0,
    manaCost: 0,
    danioMin: 90,
    danioMax: 120,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 38,
    nombre: "Metamorfosis: Gólem",
    descripcion: "Transforma al usuario en un Gólem, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    valor: 0,
    nivelRequerido: 40,
    manaCost: 1000,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 39,
    nombre: "Metamorfosis: Dragón",
    descripcion: "Transforma al usuario en un Dragón, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    valor: 0,
    nivelRequerido: 42,
    manaCost: 1300,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 40,
    nombre: "Metamorfosis: Lobo",
    descripcion: "Transforma al usuario en un Lobo, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    valor: 0,
    nivelRequerido: 15,
    manaCost: 100,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 44,
    nombre: "Metamorfosis: Oso Pardo",
    descripcion: "Transforma al usuario en un Oso Pardo, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    valor: 0,
    nivelRequerido: 20,
    manaCost: 200,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 50,
    nombre: "Metamorfosis: Tigre",
    descripcion: "Transforma al usuario en un Tigre, efecto no permanente. Las criaturas no te atacarán si aparentas ser más poderoso que ellas, y obtendrás un bonificador en tu ataque y defensa.",
    valor: 30000,
    nivelRequerido: 28,
    manaCost: 200,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 51,
    nombre: "HechizoNPCC",
    descripcion: "Hechizo de NPC.",
    valor: 0,
    nivelRequerido: 0,
    manaCost: 0,
    danioMin: 60,
    danioMax: 100,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 52,
    nombre: "Juicio final",
    descripcion: "Causa 170 a 190 puntos de daño a la victima.",
    valor: 620000,
    nivelRequerido: 42,
    manaCost: 1800,
    danioMin: 170,
    danioMax: 190,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante"],
    iconAssetPath: "/assets/ao/spells/spellNegro.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 53,
    nombre: "Portal planar",
    descripcion: "El hechizo Portal planar crea un teleport hacia tu hogar de orígen.",
    valor: 0,
    nivelRequerido: 42,
    manaCost: 2300,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante"],
    iconAssetPath: "/assets/ao/spells/spellNegro.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 54,
    nombre: "Resurrección",
    descripcion: "Revive completamente a un usuario.",
    valor: 0,
    nivelRequerido: 40,
    manaCost: 1000,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["clerigo"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 62,
    nombre: "Detectar invisibilidad",
    descripcion: "Detecta todo usuario invisible en el rango de visión del usuario.",
    valor: 200000,
    nivelRequerido: 38,
    manaCost: 1400,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo"],
    iconAssetPath: "/assets/ao/spells/spell7.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 3,
  },
  {
    idSpell: 63,
    nombre: "Lamento de la Banshee",
    descripcion: "Causa 90 a 145 puntos de daño en un área de ocho tiles.",
    valor: 820000,
    nivelRequerido: 100,
    manaCost: 3020,
    danioMin: 90,
    danioMax: 145,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 66,
    nombre: "Terror 'Rey Dragón",
    descripcion: "Hechizo de NPC.",
    valor: 0,
    nivelRequerido: 90,
    manaCost: 1440,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 67,
    nombre: "Curar heridas críticas",
    descripcion: "Curar heridas críticas, restaura entre 30 y 60 puntos de salud.",
    valor: 42000,
    nivelRequerido: 38,
    manaCost: 420,
    danioMin: 0,
    danioMax: 0,
    healMin: 90,
    healMax: 120,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["clerigo"],
    iconAssetPath: "/assets/ao/spells/furia.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 68,
    nombre: "Palabra sagrada",
    descripcion: "Hechizo deshabilitado temporalmente",
    valor: 0,
    nivelRequerido: 62,
    manaCost: 900,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["paladin"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 69,
    nombre: "Descarga flamígera",
    descripcion: "Castiga al enemigo con el fuego divino, causando entre 80 y 120 puntos de daño e incinerándolo",
    valor: 98000,
    nivelRequerido: 40,
    manaCost: 1150,
    danioMin: 130,
    danioMax: 145,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["clerigo"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 70,
    nombre: "Aura sagrada",
    descripcion: "Hechizo deshabilitado temporalmente",
    valor: 0,
    nivelRequerido: 50,
    manaCost: 720,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 71,
    nombre: "Pregonar la palabra de Dios",
    descripcion: "Cura en un diámetro de 5 tiles entre 75 y 125 puntos de vida",
    valor: 125000,
    nivelRequerido: 70,
    manaCost: 1200,
    danioMin: 0,
    danioMax: 0,
    healMin: 80,
    healMax: 100,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["clerigo"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 72,
    nombre: "Golpe certero",
    descripcion: "El receptor no fallará el próximo golpe",
    valor: 0,
    nivelRequerido: 90,
    manaCost: 400,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["paladin"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 73,
    nombre: "Poder divino",
    descripcion: "El poder del receptor aumenta considerablemente",
    valor: 0,
    nivelRequerido: 90,
    manaCost: 1160,
    danioMin: 55,
    danioMax: 70,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["paladin"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 75,
    nombre: "Círculo curativo",
    descripcion: "Curar entre 25 y 35 puntos de salud en un diámetro de 3 tiles.",
    valor: 0,
    nivelRequerido: 35,
    manaCost: 320,
    danioMin: 0,
    danioMax: 0,
    healMin: 40,
    healMax: 55,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spellDruida.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 76,
    nombre: "Semillas de fuego",
    descripcion: "Bellotas y bayas se convierten en bolas de fuego, causando 85 a 120 puntos de daño.",
    valor: 52000,
    nivelRequerido: 40,
    manaCost: 1150,
    danioMin: 120,
    danioMax: 145,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 77,
    nombre: "Rayo solar",
    descripcion: "Haz de luz que ciega e inflige 50 a 100 puntos de daño.",
    valor: 0,
    nivelRequerido: 42,
    manaCost: 1350,
    danioMin: 50,
    danioMax: 100,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 78,
    nombre: "Terremoto",
    descripcion: "Causa entre 50 y 75 puntos de daño en un radio de 3 tiles.",
    valor: 0,
    nivelRequerido: 40,
    manaCost: 880,
    danioMin: 50,
    danioMax: 75,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["druida"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 3,
  },
  {
    idSpell: 81,
    nombre: "Mirada penetrante",
    descripcion: "Hechizo de Bardo",
    valor: 0,
    nivelRequerido: 45,
    manaCost: 200,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["bardo"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 82,
    nombre: "Intimidar al espíritu",
    descripcion: "Hechizo deshabilitado temporalmente.",
    valor: 0,
    nivelRequerido: 80,
    manaCost: 75,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 83,
    nombre: "Cobijo seguro de Leomundo",
    descripcion: "Hechizo De Bardo",
    valor: 0,
    nivelRequerido: 55,
    manaCost: 360,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["bardo"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 84,
    nombre: "Lamento de las almas",
    descripcion: "Causa 130 a 145 puntos de daño al objetivo.",
    valor: 45000,
    nivelRequerido: 40,
    manaCost: 1200,
    danioMin: 130,
    danioMax: 145,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["bardo"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 85,
    nombre: "Inspiracion",
    descripcion: "Hechizo de bardo",
    valor: 0,
    nivelRequerido: 36,
    manaCost: 720,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["bardo"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 86,
    nombre: "Asistencia divina",
    descripcion: "Hechizo deshabilitado temporalmente.",
    valor: 0,
    nivelRequerido: 75,
    manaCost: 9999,
    danioMin: 0,
    danioMax: 0,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
  {
    idSpell: 87,
    nombre: "Castigo Divino",
    descripcion: "Causa 75 a 100 puntos de daño a la victima.",
    valor: 0,
    nivelRequerido: 40,
    manaCost: 570,
    danioMin: 75,
    danioMax: 100,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["paladin"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 88,
    nombre: "Fuente de vida",
    descripcion: "Hechizo deshabilitado temporalmente.",
    valor: 0,
    nivelRequerido: 60,
    manaCost: 9999,
    danioMin: 75,
    danioMax: 100,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["paladin"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 89,
    nombre: "Honor del Paladín",
    descripcion: "Hechizo deshabilitado temporalmente.",
    valor: 0,
    nivelRequerido: 100,
    manaCost: 500,
    danioMin: 100,
    danioMax: 140,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["paladin"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 92,
    nombre: "Misil mágico",
    descripcion: "Causa 25 a 35 puntos de daño a la victima.",
    valor: 0,
    nivelRequerido: 10,
    manaCost: 40,
    danioMin: 25,
    danioMax: 35,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 93,
    nombre: "Descarga Eléctrica",
    descripcion: "Causa 35 a 60 puntos de daño a la victima.",
    valor: 26000,
    nivelRequerido: 26,
    manaCost: 250,
    danioMin: 50,
    danioMax: 75,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 94,
    nombre: "Ráfaga ígnea",
    descripcion: "Causa 55 a 70 puntos de daño a la victima.",
    valor: 34000,
    nivelRequerido: 32,
    manaCost: 720,
    danioMin: 75,
    danioMax: 95,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spellFuerte.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 100,
    nombre: "Curar heridas graves GMs",
    descripcion: "Curar heridas graves, restaura La vida entera.",
    valor: 0,
    nivelRequerido: 0,
    manaCost: 0,
    danioMin: 0,
    danioMax: 0,
    healMin: 5000,
    healMax: 5000,
    puedeUsarseEnAliados: true,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: false,
    aoeRadiusTiles: 0,
  },
  {
    idSpell: 101,
    nombre: "Apocalipsis GMs",
    descripcion: "Causa 50 a 90 puntos de daño en un area de cuatro tiles.",
    valor: 0,
    nivelRequerido: 80,
    manaCost: 1,
    danioMin: 500,
    danioMax: 900,
    healMin: 0,
    healMax: 0,
    puedeUsarseEnAliados: false,
    remueveDebuff: null,
    usableBy: ["mago", "nigromante", "druida", "bardo", "paladin", "clerigo", "asesino"],
    iconAssetPath: "/assets/ao/spells/spell_default.png",
    isStarter: false,
    aoe: true,
    aoeRadiusTiles: 2,
  },
];
